---
title: "How to cite information from the NBA"
title-block-banner: "#adb5bd"
title-block-banner-color: white
---

*The online form of the NBA will allow updates of certain indicators more regularly, making the NBA a ‘living’ assessment that reflects the most current data available. It is therefore important to use the recommended citation approach below.*

## Technical pages

To reference the technical pages of this website (those with an author list at the top of the page) please use the **Recommended citation** **at the bottom of each page**.

*Example:*

-   Da Silva, J.M., Nieto Lawrence, J.A., & Tolley, K.A. 2025. Genetic diversity. National Biodiversity Assessment 2025. South African National Biodiversity Institute. https://nba.sanbi.org.za/.

## General pages

Some pages on the site do not have a specific author list or recommended citation, and this general NBA content should be referenced as follows:

-   South African National Biodiversity Institute (SANBI). 2025. National Biodiversity Assessment 2025: The status of South Africa’s biodiversity - Website. South African National Biodiversity Institute (an entity of the Department of Forestry, Fisheries and the Environment), Pretoria. <https://nba.sanbi.org.za/>

## nbaR package

The NBA website is built using [R](https://www.r-project.org/) and [Quarto](https://quarto.org/). Tables and figures are generated using the [nbaR package](https://sanbi-nba.github.io/nbaR/). Recommended citation:

-   Besseling N, Hendricks S, Bull L, Monyeki M, von Staden L (2025). nbaR: Package for creation of the NBA. Available at <https://github.com/SANBI-NBA/nbaR>. [doi:10.5281/zenodo.14899426](https://doi.org/10.5281/zenodo.14899426).

## A note on dates and releases

The NBA aims to draw on the best available biodiversity data and analyses and present these periodically in a national report. As such, the NBA 2025 draws on input datasets from a range of sources, each with its own update and release cycle. For example the marine ecosystem map was published in 2023 and this informed the various ecosystem assessments that were conducted in 2024/2025; the spider Red List assessment was conducted in 2020 but continues to represent the best available data in 2025.

With the development of the NBA website, regular updates of indicators are now possible. The 'What's new' section will highlight updates and new content, ensuring the best available information is accessible, while archiving content that has been superseded.
