---
title: "Media and other resources" # 
title-block-banner: "#adb5bd"
title-block-banner-color: white
bibliography: refs-about-nba.bib
---

### Media resources and popular products

Access a range of National Biodiversity Assessment media releases and multi-media products via these links.

**Short films:**

-   The Flow for Life – a \~3 min film speaking to NBA 2025’s key messages on clean freshwater flowing to the sea, pollution and the threat status of South Africa’s rivers, wetlands and estuaries

Note: more short films will be added during 2026.

**Social media teaser news items:**

Several social media teasers were published just before the release of NBA 2025. These were the longer news items linked to some of those teasers:

-   [Twenty years of the NBA – tracking progress, challenges, and change](https://www.sanbi.org/news/twenty-years-of-the-nba-tracking-progress-challenges-and-change/)

-   [Genetic diversity, a new lens on biodiversity](https://www.sanbi.org/news/why-measuring-genetic-diversity-matters-for-south-africas-future/)

*We also welcome our scientific partners and partners in the fields of education, citizen science and communication to make non-technical materials about any of the NBA 2025 findings or key messages. Just let us know via the NBA email address so that we can also repost and share.*
