---
title: "News and updates"
title-block-banner: "#adb5bd"
title-block-banner-color: white
toc: true
toc-title: "Updates"
toc-depth: 4
---

## 2026

### Core Data Team wins prestigious NSTF-South 32 Data for Research Award {#update-nstf-award}

::: {.update-date .date}
16 July 2026
:::

For 28 years, the NSTF-South32 Awards have celebrated outstanding contributions by researchers, innovators, science communicators, data specialists and research leaders whose work shape South Africa’s future and advance global knowledge. The NBA 2025 Core Data Team was awarded the prestigious Data for Research Award at a gala ceremony on Thursday 16 July 2026. The award recognised the transformation of the NBA into an innovative, web-based living assessment that enables users to move seamlessly from high-level findings to the underlying data, methods and analyses, significantly improving the accessibility, transparency and long-term value of South Africa’s biodiversity evidence base. [Read more »](https://nstf.org.za/wp-content/uploads/2026/07/26WinnersMediaReleaseDatabase.pdf)

------------------------------------------------------------------------

### NBA 2025 webinar series concludes {#update-nba-webinars}

::: {.update-date .date}
19 June 2026
:::

The findings of the NBA 2025 were showcased in a series of 10 webinars. The concluding webinar was presented on 19 June 2026 and reflected on the key themes and insights shared throughout the series as well as exploring what lies ahead for biodiversity assessment, monitoring and reporting in South Africa. Links to recordings of all 10 webinars can be found on our [media page](../context/media.qmd#webinars).

------------------------------------------------------------------------

### NBA 2025 spatial data now available on BGIS {#update-spatial-data}

::: {.update-date .date}
1 June 2026
:::

Spatial datasets associated with realm assessments for the NBA 2025 are now available for download on [SANBI's Biodiversity GIS website](https://bgis.sanbi.org/Projects/Detail/2286). These include ecosystem threat status and protection levels, remaining natural extent (for terrestrial ecosystems), and ecological condition data for estuaries and marine ecosystems.

## 2025

### What's new in the NBA 2025

::: {.update-date .date}
8 December 2025
:::

The focus of NBA 2025 was on creating transparent and repeatable workflows hosted on accessible repositories, and ensuring that the entirety of the results expected in the NBA are online via a searchable website. In addition, there was also substantial new work that was accomplished between the release of NBA 2018 and the release of NBA 2025. The following is what is new in NBA 2025:

-   **Excellent progress has been made regarding automated condition assessments** **inland wetlands** to support the NBA 2025 threat assessments; NBA 2025 provides interim regional wetland types while a rigorous update of the typology is underway to provide more detailed characterisations; and work towards a revised National Wetland Map remains ongoing using a multi-partner, mixed approach that integrates GIS-based wetland predictive modelling, remote sensing and specialist mapping and validation (both field and desktop). [Read more »](../freshwater/fw_wet_condition.qmd)

-   **River** **condition data (PES) was updated** nationally as part of a WRC project and this data was used to update and improve river ecosystem threat status and protection level assessments. [Read more »](../freshwater/fw_riv_condition.qmd)

-   **The** **Marine Ecosystem Map** **Version 2023** is used in this NBA and represents a minor update to the 2018 map, with the reintroduction of a pelagic layer in deeper waters beyond the shelf. In the meantime, a data-driven framework for updating the map has been in development and will represent a more substantial update in time for the next NBA. Condition data was not updated, however assessment methods have been improved. [Read more »](../marine/marine_ecosystems.qmd)

-   **The new version of the** **Vegetation Map** of South Africa, released in early 2025, informed the terrestrial ecosystem assessments. [Read more »](../terrestrial/ter_ecosystems.qmd)

-   **Various research and mapping projects have made new data available on the distribution and abundance of invasive alien plants**; these data have been used to improve terrestrial ecosystem threat status and protection level assessments. [Read more »](../terrestrial/ter_ets.qmd)

-   **The NBA shows** **trends in terrestrial ecosystem threat status** with one of the world’s first applications of the Red List Index for ecosystems (RLIe), showing trends in ecosystem risk. The index can be disaggregated using national biomes or the IUCN Global Ecosystems Typology Level 3 – the latter useful for international comparisons. [Read more »](../terrestrial/ter_ets.qmd)

-   **Trends in ecosystem protection level** in the terrestrial realm are explored using the new Ecosystem Protection Level Index. [Read more »](../terrestrial/ter_epl.qmd)

-   **Three new taxonomic groups** have been included in NBA 2025: freshwater crabs, Anostraca (fairy shrimps) and spiders, and revised assessments of birds, mammals, reptile and amphibians have improved the Red List Index that tracks changes in threat status over time. [Read more »](../species/sp.qmd)

-   Building on the efforts begun for NBA 2018, the genetic component of the NBA now pilots **international indicators of genetic diversity**. [Read more »](../genetics/genetic-indicators.qmd)

-   **Updated biodiversity tourism statistics**, based on Statistics South Africa’s 2024 publication of Experimental Biodiversity based Tourism Estimates for South Africa, are used in the benefits of biodiversity infographic. [Read more »](./importance.qmd)
