{
  "hash": "85ae693d1f89c1eb56588ecc2741eff6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Spiders\" \nsubtitle: \"\" \n\ntitle-block-banner: \"#ad180d\" \ntitle-block-banner-color: white \n\nauthor:\n  - name:\n      given: Ansie\n      family: Dippenaar-Schoeman\n    orcid: 0000-0003-1532-1379\n    affiliations:\n      - ref: arc\n  - name:\n      given: Robin\n      family: Lyle\n    orcid: 0000-0002-5279-5306\n    affiliations:\n      - ref: arc    \n  - name:\n      given: Domitilla C\n      family: Raimondo\n    orcid: 0000-0003-3998-752X\n    affiliations:\n      - ref: sanbi    \n  - name:\n      given: Theresa \n      family: Sethusa\n    orcid: 0000-0001-6330-6531\n    affiliations:\n      - ref: sanbi\n  - name:\n      given: Stefan \n      family: Foord\n    orcid: 0000-0002-9195-2562\n    affiliations:\n      - ref: uv\n  - name:\n      given: Charles\n      family: Haddad\n    orcid: 0000-0002-2317-7760\n    affiliations: \n      - ref: ufs\n  - name: \n      given: Leon\n      family: Lotz\n    orchid: 0009-0009-3370-2520 \n    affiliation:\n      - ref: nmb\n  - name:\n      given: Shae-Lynn E.\n      family: Hendricks\n    orcid: 0009-0003-1733-1156\n    affiliations:\n      - ref: sanbi \n  - name:\n      given: Maphale S.\n      family: Monyeki\n    orcid: 0000-0002-5083-7461\n    affiliations:\n      - ref: sanbi     \n  - name: \n      given: Dewidine \n      family: van Der Colff \n    orcid: 0000-0002-0906-7098\n    affiliations:\n      - ref: sanbi\n     \naffiliations:\n  - id: arc \n    number: 1 \n    name: Agricultural Reseach Council\n\n  - id: sanbi \n    number: 2 \n    name: South African National Biodiversity Institute\n  - id: uv\n    number: 3\n    name: University of Venda\n  - id: ufs\n    number: 4\n    name: University of the Free State\n  - id: nmb\n    number: 5\n    name: National Museum Bloemfontein\n\ndate: last-modified\nbibliography: species.bib\n\ncitation:\n  type: webpage\n  container-title: National Biodiversity Assessment 2025\n  publisher: South African National Biodiversity Institute\n  url: http://nba.sanbi.org.za/\n\nappendix-cite-as: false\ngoogle-scholar: true\nimage: \"./imgs/sp_spider_img_1.png\"\n---\n\n```{=html}\n<style>\n\n.inline-style-endemic {\n  color: #FFEBB0;\n  font-size: 300%;\n  font-weight: 600;\n}\n.inline-style-rare {\n  color: #C1B5A5;\n  font-size: 300%;\n  font-weight: 600;\n}\n\n.img-align {\n  width: 400;\n  height: 180px;\n  object-fit: cover;\n  border-radius: 10px;\n}\n\n.img-align1 {\n  width: 80%;          \n  height: 230px;        \n  display: block;\n}\n\n\n</style>\n```\n\n![*Pycnacantha tribulus* (Fabricius, 1781), the hedgehog spider, was the first spider species described from South Africa, 244 years ago. (© Peter Webb)](./imgs/sp_spider_img_1.png){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n:::::: columns\n::: {.column width=\"33.3%\"}\n<center>\n\n| [78]{.inline-style-threatened}\n| of 2 214 species assessed are\n| [Threatened]{.inline-style-indicator}\n\n</center>\n:::\n\n::: {.column width=\"33.3%\"}\n<center>\n\n| [60]{.inline-style-rare}\n| of 2 214 species assessed are\n| [Rare or Critically Rare]{.inline-style-indicator}\n\n</center>\n:::\n\n::: {.column width=\"33.3%\"}\n<center>\n\n| [1 303]{.inline-style-endemic}\n| species of spiders (58%) are\n| [Endemic]{.inline-style-indicator}\n\n</center>\n:::\n::::::\n\n------------------------------------------------------------------------\n\n## Key findings\n\n-   South Africa has a rich diversity of spider species, with 2 265 described species [@a2023a], representing 4% of the world's spiders.\n\n-   A comprehensive assessment of 2 214 spider species was conducted for the first time between 2016 and 2019 using the IUCN Red List of Threatened Species Categories and Criteria. This assessment is a global first and a pioneering effort in applying IUCN Red List criteria to a mega-diverse invertebrate group [@foord2020a].\n\n-   The spider assessment was made possible through the 22-year South African National Survey of Arachnida (SANSA) initiative, which resulted in significant improvements to the knowledge base: a 33% increase in described species and, during this project, a 350% rise in specimen accessions in the national collection.\n\n-   Of the assessed species, only 78 of the species (4%) were assessed as threatened.\n\n-   Most species (1 419 species, 64%) are widely distributed with no known threats and are assessed as Least Concern.\n\n-   Importantly, almost a third of the species (707 species, 32%) are assessed as Data Deficient, meaning that a large number of species need further research before their risk of extinction can be determined.\n\n-   Endemism is high, with 1 303 species (58%) found only in South Africa, representing around 2% of the world’s spiders.\n\n-   In the IUCN Red List Index (RLI) assessment, spiders currently have the highest RLI score of all South African taxonomic groups, making them appear the least threatened. However, many species remain unevaluated due to limited information. As a result, their true status is uncertain – more species may prove to be threatened, or many may be Least Concern. This uncertainty means the current RLI value should be interpreted with caution.\n\n-   The major threats to spiders are habitat loss due to fire, overgrazing, invasive plants, mining, agricultural practices, and urban development.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Threatened spider richness across South Africa, mapped as the number of threatened species per 10 x 10 km grid cell.](./imgs/spiders_thrt_10km_HD.png){#fig-1 width=650px}\n:::\n:::\n\n\n## Threat status\n\nIn 2016, South Africa assessed 2 214 indigenous spider species for the first time using the IUCN Red List categories and criteria, which measure extinction risk [@foord2020a]. Of the assessed species, 78 (4%) were threatened with extinction: 23 are Critically Endangered (CR), 24 are Endangered (EN), and 31 are Vulnerable (VU). No species were found to be extinct or possibly extinct.\n\nHighly threatened spiders occur in the three major urban centres of South Africa (Western Cape, Gauteng and KwaZulu-Natal). This could be an indication of sample bias, but also identifies areas that have lost large areas of habitat to urban expansion (@fig-1). Some species have very restricted ranges yet face no anthropogenic threats. These are listed under [South Africa’s national rarity categories](https://redlist.sanbi.org/redcat.php): Rare (extent of occurrence \\<500 km²) or Critically Rare (known from a single location). Sixteen spider species were classified as Critically Rare and 44 species as Rare. Although such species are assessed as Least Concern under the IUCN system, they remain a priority for national conservation and are included as taxa of conservation concern along with threatened, Near Threatened and Data Deficient species.\n\nMost species (1 419, 63%) are widespread, face no known threats, and are assessed as Least Concern (@fig-2). A large proportion (675, 30%) are Data Deficient, highlighting the need for more research, particularly providing more detailed taxonomic descriptions, describing unknown sexes and providing additional distribution data through field sampling and examination of museum material (see @box-1).\n\nEndemism is high, with 1 325 species (59%) found only in South Africa, representing 2% of global spider diversity. Of the 72 spider families recorded, Salticidae (jumping spiders) is the most species-rich (354), followed by Gnaphosidae (195) and Thomisidae (143) [@a2023a]. Because of its size, Salticidae also has the highest number of threatened (6) and Data Deficient (98) species.\n\nHowever, the greatest conservation concern lies with smaller, cryptic species in isolated habitats such as caves and fragmented habitats. Families such as Pholcidae, Archaeidae, and Corinnidae each include four threatened species. Families with the highest numbers of Rare or Critically Rare species are Pholcidae (18), Salticidae (5) and Drymusidae (4) [@foord2020a].\n\n:::: panel-tabset\n## Figure\n\n<!-- it is important to use second-level headings in panel tabsets, i.e. two hashes -->\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Threat status of 2&nbsp;214 South African spider species assessed following the IUCN 3.1 Red List Categories and Criteria. The portion of species in each category is shown in the larger circle (A), and the proportion of endemic species per category is shown in the smaller circle (B). The total number of taxa assessed is shown in the inner circle.](sp_spiders_files/figure-html/fig-2-1.png){#fig-2 width=100% height=auto}\n:::\n:::\n\n\n## Data\n\n<!--# If the table is long use the div to give it a vertical scroll bar. Otherwise the div can be excluded. -->\n\n::: {#table .table style=\"height:500px;overflow-y: auto\"}\n\n::: {#tbl-1 .cell .plain tbl-cap='Summary statistics of all South African indigenous spiders and endemics, the number of species within each IUCN Red List category are indicated.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ybzjobakgv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ybzjobakgv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ybzjobakgv thead, #ybzjobakgv tbody, #ybzjobakgv tfoot, #ybzjobakgv tr, #ybzjobakgv td, #ybzjobakgv th {\n  border-style: none;\n}\n\n#ybzjobakgv p {\n  margin: 0;\n  padding: 0;\n}\n\n#ybzjobakgv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 12px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ybzjobakgv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ybzjobakgv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ybzjobakgv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ybzjobakgv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ybzjobakgv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ybzjobakgv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ybzjobakgv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ybzjobakgv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ybzjobakgv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ybzjobakgv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ybzjobakgv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ybzjobakgv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ybzjobakgv .gt_row {\n  padding-top: 12px;\n  padding-bottom: 12px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ybzjobakgv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybzjobakgv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ybzjobakgv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ybzjobakgv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ybzjobakgv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybzjobakgv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ybzjobakgv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybzjobakgv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ybzjobakgv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybzjobakgv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ybzjobakgv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybzjobakgv .gt_left {\n  text-align: left;\n}\n\n#ybzjobakgv .gt_center {\n  text-align: center;\n}\n\n#ybzjobakgv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ybzjobakgv .gt_font_normal {\n  font-weight: normal;\n}\n\n#ybzjobakgv .gt_font_bold {\n  font-weight: bold;\n}\n\n#ybzjobakgv .gt_font_italic {\n  font-style: italic;\n}\n\n#ybzjobakgv .gt_super {\n  font-size: 65%;\n}\n\n#ybzjobakgv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ybzjobakgv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ybzjobakgv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ybzjobakgv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ybzjobakgv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ybzjobakgv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ybzjobakgv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ybzjobakgv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ybzjobakgv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;width:100%;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:15%;\"/>\n    <col style=\"width:10%;\"/>\n    <col style=\"width:10%;\"/>\n    <col style=\"width:10%;\"/>\n    <col style=\"width:10%;\"/>\n    <col style=\"width:10%;\"/>\n    <col style=\"width:10%;\"/>\n    <col style=\"width:10%;\"/>\n    <col style=\"width:10%;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: left;\" scope=\"col\" id=\"Taxon\">Taxon</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: center;\" scope=\"col\" id=\"Critically-Endangered\">Critically Endangered</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: center;\" scope=\"col\" id=\"Endangered\">Endangered</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: center;\" scope=\"col\" id=\"Vulnerable\">Vulnerable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: center;\" scope=\"col\" id=\"Near-Threatened\">Near Threatened</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: center;\" scope=\"col\" id=\"Data-Deficient\">Data Deficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: center;\" scope=\"col\" id=\"Rare\">Rare</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: center;\" scope=\"col\" id=\"Least-Concern\">Least Concern</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: center;\" scope=\"col\" id=\"Total\">Total</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Taxon\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Overall spiders</td>\n<td headers=\"Critically Endangered\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">6</td>\n<td headers=\"Endangered\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">26</td>\n<td headers=\"Vulnerable\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">37</td>\n<td headers=\"Near Threatened\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">8</td>\n<td headers=\"Data Deficient\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">675</td>\n<td headers=\"Rare\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">60</td>\n<td headers=\"Least Concern\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">1402</td>\n<td headers=\"Total\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">2214</td></tr>\n    <tr><td headers=\"Taxon\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Endemic spiders</td>\n<td headers=\"Critically Endangered\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">6</td>\n<td headers=\"Endangered\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">26</td>\n<td headers=\"Vulnerable\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">37</td>\n<td headers=\"Near Threatened\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">8</td>\n<td headers=\"Data Deficient\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">657</td>\n<td headers=\"Rare\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">57</td>\n<td headers=\"Least Concern\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">482</td>\n<td headers=\"Total\" class=\"gt_row gt_right\" style=\"text-align: center; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">1273</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n::::\n\n:::: {#box-1 .callout-note .species collapse=\"true\"}\n## Box 1. The South African National Survey of Arachnida (SANSA)\n\nThe South African National Survey of Arachnida (SANSA) was initiated in 1997, with the aim of documenting the arachnid fauna of South Africa at a national level and to unify and strengthen biodiversity research on the spiders of South Africa [@dippenaar-schoeman2015a]. SANSA was managed by the Arachnida Unit at the National Collection of Arachnida (NCA) at the Agricultural Research Council - Plant Health and Protection (ARC-PHP) unit in Pretoria, with support from the Universities of the Free State and Venda, the National Museum in Bloemfontein, and the South African National Biodiversity Institute (SANBI) Threatened Species Programme, who funded SANSA Phase 2 [@dippenaar-schoeman2015a].\n\nThe primary objective of the SANSA Phase 1 (1997–2005) was to consolidate all existing spider data into a relational database developed at the ARC. The study of South African spiders was significantly influenced by colonial expansion and the visits of scientists, who dispatched hundreds of specimens to museums in Belgium, France, Germany and the United Kingdom. The data date back to 1781, when the first species was described from South Africa. Records of all known South African species and their distribution information were extracted from original descriptions, re-descriptions and revisionary work, as listed on the World Spider Catalogue. SANBI joined the project for its second phase, known as SANSA II, from 2006 to 2010. Gap analyses were done to determine the spatial coverage of the species, and targeted surveys were undertaken throughout South Africa, particularly in areas with poor historic coverage. Due to extensive fieldwork by SANSA field managers and research from other projects, student projects and public participation, more than 40 degree-squares were sampled in previously poorly sampled areas, providing valuable material that improved our knowledge of species distributions and yielding valuable specimens for future taxonomic studies. In 2010, the [First Atlas of South African Spiders](https://zenodo.org/records/7628809) (FASSA) was published online, listing 2003 species from 70 families, with georeferenced records and distribution maps [@a2010a]. The last decade has seen considerable growth in the knowledge of spiders in South Africa, and the number of species known from the country has increased to 2 265 species [@a2023a]. Dr Dippenaar-Schoeman still continues to work on the SANSA project as the project manager, updating taxonomy, even after retiring from the ARC-PHP.\n\n![](./imgs/sp_spider_img_2.png){style=\"border-radius:10px;\"}[The National Collection of Arachnida - The cabinets housing the specimens in the National Collection of Arachnida. (© Elsa van Niekerk)]{style=\"width:75%; color:#626262;\"}\n\n::: {style=\"display: flex; justify-content: center; gap: 10px; flex-wrap: wrap;\"}\n<figure style=\"margin: 0; text-align: left; flex: 1 1 45%;\">\n\n<img src=\"./imgs/sp_spider_img_3.png\" style=\"width:100%; height:250px; object-fit: cover; border-radius:10px; margin: 0\"/>\n\n<figcaption>Fogging trees at Lajuma, Limpopo province to sample arachnids in the tree canopy. (© Elsa van Niekerk)</figcaption>\n\n</figure>\n\n<figure style=\"margin: 0; text-align: left; flex: 1 1 45%;\">\n\n<img src=\"./imgs/sp_spider_img_5.png\" alt=\"Habitat monitoring\" style=\"width:100%; height:250px; object-fit: cover; border-radius:10px; margin: 0\"/>\n\n<figcaption>SANBI parataxonomist learning to collect spiders. <br> (© Robin Lyle)</figcaption>\n\n</figure>\n:::\n::::\n\n## Trends – the Red List Index\n\nThe trend in spider extinction risk was measured using a global standard indicator, the IUCN Red List Index (RLI) of species [@butchart2004a]. The RLI is calculated for each taxonomic group based on genuine changes in Red List categories over time. The RLI value ranges from 0 to 1. At a value of 1, all species are at low risk of extinction (Least Concern), while a value of 0 indicates that all species are extinct. The RLI value for spiders in South Africa was calculated in 2020 and included 2 214 species. The RLI value is 0.994, and relative to other taxon groups assessed in South Africa, spiders have the highest RLI value (@fig-3). Since only one assessment has been conducted for spiders, it is not possible to determine the trend in extinction risk for this group. It is important to note that many Data Deficient species are included in the assessment, and hence there is still a high level of uncertainty associated with this result.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The first Red List Index (RLI) for spider species assessed in South Africa, relative to national aggregate, the national average RLI across all assessed taxonomic groups.](sp_spiders_files/figure-html/fig-3-1.png){#fig-3 width=672}\n:::\n:::\n\n\n## Pressures\n\nSpiders face an array of threats – both natural and human-driven (@fig-4). Research has shown that habitat loss caused by fire (see @box-2), overgrazing and invasive alien species infestations have a direct impact on spider populations, causing local losses [@dippenaar-schoeman2015a]. Urban expansion, agriculture, forestry, and mining are the leading causes of habitat loss for spiders. These pressures are especially important for ground-dwelling and endemic species with poor dispersal abilities. In South Africa, many spider species are highly localised and endemic to specific biomes, such as fynbos [@dippenaar-schoeman2024a] with 28% endemic species to this biome, and savanna [@foord2011a] with 30% of the species endemic. Ground-dwelling spiders are particularly vulnerable to changes in their habitat and often struggle to recolonise areas after disturbance due to their limited dispersal capabilities, making them more prone to local extinction.\n\nSpiders are present in relatively high numbers in agro-ecosystems. However, it has been shown that they are negatively impacted by pesticide use [@dippenaar-schoeman2013a]. Thus far, 51 families from 413 species have been recorded from crops in South Africa, and five agrobiont species have been identified that play an important role as natural control agents of agricultural pests. However, chemical use can directly kill spiders or disrupt their prey base. Integrated pest management (IPM) and organic farming are recommended to reduce chemical exposure that harms spiders and their prey. Altered temperature and rainfall patterns (likely from climate change) can affect spider distribution, reproduction, and prey availability, and they may be severely impacted by drought.\n\nSome spiders are threatened due to poaching and are used as pets such as the species in the Theraphosidae family [(baboon spiders)](https://www.inaturalist.org/observations?captive=false&place_id=6986&quality_grade=research&taxon_id=47424&verifiable=any). Baboon spiders are ecologically significant predators within South African ecosystems, contributing to the population regulation of a variety of insect species [@campbell2018a]. Tthreats from illegal collection for the exotic pet trade are increasing, driven by their popularity among arachnid enthusiasts. Depleted wild populations can take a long time to recover, due to the species' long lifespans and low reproductive rates [@campbell2018a; @a2010a]. Although national legislation provides protection for baboon spiders, enforcement remains inconsistent, and improved regulatory measures are needed to prevent unsustainable collecting from the wild [@campbell2018a].\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Key pressures affecting threatened and Near Threatened South African spiders. Pressures are categorised using the IUCN Threat Classification Scheme and are ranked from most to least frequent number of impacted species.](sp_spiders_files/figure-html/fig-4-1.png){#fig-4 width=100%}\n:::\n:::\n\n\n::: {#box-2 .callout-note .species collapse=\"true\"}\n## Box 2. Spider species' ability to respond to fire events, a natural ecological process that is expected to become much more frequent and unpredictable in a changing climate\n\nMost of the studies of spider ecology in South Africa are local-scale studies focusing on spider assemblage responses to habitat complexity, landscape-scale variables, ecosystem rehabilitation and plant invasions, and disturbance effects such as fire [@haddad2015a], grazing [@jansen2013a], invasive plants [@robbertson2011a] and chemical control [@berg1990a].\n\nFire is a factor that can significantly impact spider populations, but its effects vary depending on the species, habitat, and intensity of the fire. Many foliage-dwelling spiders perish during fires due to direct exposure to heat and flames, while some ground-dwellers that remain in their burrows (particularly trapdoor spiders) and those that seek shelter under rocks or in cracks in the soil are less impacted. Due to habitat disruption, fire alters leaf litter, vegetation and micro-habitats that spiders rely on for shelter and hunting. A study in central South African grasslands found that fast-burning spring fires resulted in an immediate sharp decline in ground-dwelling spider numbers, but that assemblages recovered to levels comparable to unburnt sites within a year. Burnt sites had significantly fewer individuals and species compared to unburnt ones. Some families, such as Lycosidae (wolf spiders) and Gnaphosidae (ground spiders), persisted post-fire, while others declined. Caponiidae (lungless spiders) were the only group found to increase in burnt areas. Studies have shown a decline in overall spider numbers after fire events. There are species-specific responses, and web builders (such as orb and sheet weavers) are more vulnerable and often absent after a fire, while ground hunters and ambush predators tend to be more resilient. Some spiders can recolonise burned areas relatively quickly, depending on the severity of the fire and the condition of the surrounding habitat. Fires that burn unevenly leave refuges that aid in faster recovery [@haddad2015a].\n\n![](./imgs/sp_spiders_img_6.png){style=\"border-radius:10px;\"}[Veld fire in a savannah ecosystem. (© Robin Lyle)]{style=\"width:75%; color:#626262;\"}\n:::\n\n## Knowledge gaps\n\nA significant portion of the South African spider fauna remains undescribed. In the Cape Floristic Region, 24% of species are classified as Data Deficient, and two families (Synotaxidae and Theridiosomatidae) are only known from undescribed species. Studies on mygalomorph trapdoor spiders (e.g. *Stasimopus*, *Ancylotrypa*, *Galeosoma*) show taxonomic resolution as low as 15–29%, indicating high uncertainty in species delimitation.\n\nSampling bias and geographic gaps are a concern. Spider records are heavily concentrated in the eastern and coastal regions of South Africa, with North West, Northern Cape and Mpumalanga province remaining undersampled [@foord2020a; @a2023a; @mescht2024a]. These sampling biases impede conservation assessments and ecological modelling. Making use of citizen science to contribute to observations, both helps fill sampling gaps and also raises awareness (see @box-3).\n\n::: {#box-3 .callout-note .species title=\"Box 3. Calling all citizen scientists!\" collapse=\"true\"}\nTo contribute to the future Red List assessments and monitoring of spiders, join iNaturalist!\n\n<center>[Spiders of South Africa iNaturalist](https://www.inaturalist.org/projects/spiders-of-south-africa)</center>\n\n<br> New to iNaturalist (or never heard of it) and want to play along? Watch these [**video tutorials**](https://inaturalist.freshdesk.com/en/support/solutions/folders/151000547795) to get started, and sign up on the iNaturalist website or download the app on your smartphone.\n\nTo see how valuable your nature photographs can be, watch this inspiring [**TED talk**](https://www.ted.com/talks/148410).\n\n<center>![](./imgs/sp_logo_inat.png){width=\"10%\" style=\"border-radius:10px;\"}</center>\n:::\n\nMorphological variation is poorly understood due to limited sampling, making it difficult to confidently define species boundaries. Despite SANSA’s efforts, many natural history collections lack comprehensive coverage or standardised metadata, limiting their utility for taxonomic synthesis. Large numbers of specimens in collections remain unidentified due to a lack of spider taxonomists. For example, a recent meta-analysis of South African spider data from seven collections found that only slightly more than half of around 121 000 records had been identified to species level, indicating a major taxonomic gap in the available data [@mescht2024a]. Presently, there is only one spider taxonomist employed at a natural history collection. The shortage of taxonomic expertise will have direct consequences for resolving Data Deficient taxa and developing taxonomic products related to species descriptions, revisions, and the integration of molecular tools.\n\nAddressing the taxonomic impediment for spiders in South Africa requires a multi-pronged strategy that blends capacity building, infrastructure development, and policy integration. The following is a breakdown of suggested solutions:\n\n-   Expansion of taxonomic capacity by creating employment for specialist taxonomists and providing the required skills transfer opportunities (see @box-4).\n\n-   Accelerate species descriptions through capacity building and collaborative research, particularly with international partners.\n\n-   Integrate molecular tools and promote DNA barcoding and phylogenetics to resolve species boundaries, especially in morphologically conservative groups.\n\n-   Develop a national spider barcode reference library linked to voucher specimens and ecological metadata. Currently, sequence data on South African spiders (around 10  600 specimens processed, mainly COI-5P) is scattered among several projects with strongly contrasting levels of taxonomic resolution.\n\n-   Digitize and standardise collections with high-resolution imaging, georeferencing, and standardised metadata.\n\n-   Support the evolution of natural science collection databases to be more accessible by improving the use of centralized database accessible to researchers, conservationists, and policy-makers.\n\n-   Encourage citizen science platforms like iNaturalist to crowdsource observations and expand distribution data (see @box-3).\n\n-   Relax permit conditions so that members of the public can sample specimens without fear of prosecution, particularly those linked to photographic observations, to enable species-level identifications.\n\n-   Link taxonomic work to spatial tools for species conservation, e.g. Key Biodiversity Areas (KBAs) and the [DFFE's Environmental Screening Tool](https://screening.environment.gov.za/screeningtool/#/pages/welcome) for Environmental Impact Assessments (EIAs), to justify funding and urgency. This can be further linked to understanding biodiversity data and the role it could play in South Africa’s biosecurity with regards to emerging pests and diseases.\n\n-   Foster international collaboration and partner with global arachnological networks for training, data sharing, and joint revisions.\n\n-   Invite and fund visiting taxonomists to work on South African material and co-author species descriptions.\n\n-   Facilitate the training of taxonomists from other African countries to expand the skills base on the continent.\n\n:::::::::::::::::::: {#box-4 .callout-note .species collapse=\"true\"}\n## Box 4. Data Deficient spiders of South Africa\n\nSouth Africa has the richest known spider fauna on the African continent, with a long history of taxonomic research. In spite of this, much work remains to be done. Many families have never been subjected to taxonomic revision and continue to present a considerable identification challenge to taxonomists and ecologists alike. Surveys and research have shown that a large proportion of species remain undescribed in several families. For example, the National Collection of Arachnida has around 45% of specimens that are still unidentified.\n\nPreliminary research on the following families reveals that many species remain unidentified. All images are credited to © Peter Webb unless otherwise indicated.\n\n::::::::::::::::::: grid\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![*Araneus coccinella* [Araneidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=47535) (estimated to be 29 spp.)](./imgs/sp_spider_img_7.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![*Clubiona durbana* [Clubionidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=121773) (estimated to be 150 spp.)](./imgs/sp_spiders_img_8.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![*Copuetta lacustris* [Corinnidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=47418) (estimated to be 14 spp.)](./imgs/sp_spiders_img_9.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![*Dictyna sp.* [Dictynidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=84523) (estimated to be 6 spp.)](./imgs/sp_spiders_img_10.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![*Afrofilistata fradei* [Filistatidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=49331) (estimated to be 6 spp.) (© G. Wilson)](./imgs/sp_spiders_img_11.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![*Aphantaulax* sp. [Gnaphosidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=50168) (estimated to be 10 spp.)](./imgs/sp_spiders_img_12.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![Macrobunidae sp. [Macrobunidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=1525719) (estimated to be 13 spp.)](./imgs/sp_spiders_img_13.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![Mimetidae sp. [Mimetidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=60351) (estimated to be 8 spp.)](./imgs/sp_spiders_img_14.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![Orsolobidae sp. [Orsolobidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=373104) (estimated to be 3 spp.)](./imgs/sp_spiders_img_15.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![*Peucetia striata* [Oxyopidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=83843) (estimated to be 15 spp.)](./imgs/sp_spiders_img_16.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![Philodromidae sp. [Philodromidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=47868) (estimated to be 6 spp.)](./imgs/sp_spiders_img_17.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![Scytodidae sp. [Scytodidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=47431) (estimated to be 80 spp.)](./imgs/sp_spiders_img_18.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![Selenopidae sp. [Selenopidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=47487) (estimated to be 23 spp.)](./imgs/sp_spiders_img_19.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![*Latrodectus cinctus* [Theridiidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=47371) (estimated to be 28 spp.)](./imgs/sp_spiders_img_20.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![*Afroceto martini* [Trachelidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=416721) (estimated to be 35 spp.)](./imgs/sp_spiders_img_21.png){.img-align}\n:::\n\n::: {.g-col-lg-3 .g-col-6 .text-left}\n![Zodariidae sp. [Zodariidae](https://www.inaturalist.org/observations?place_id=6986&taxon_id=48893) (estimated to be 8 spp.)](./imgs/sp_spiders_img_22.png){.img-align}\n:::\n:::::::::::::::::::\n::::::::::::::::::::\n\n## Approach\n\n### Threat status assessments\n\nThe first IUCN Red List assessment of South African spiders was conducted between 2016 and 2019, as a collaborative project between the South African National Biodiversity Institute (SANBI), the Agricultural Research Council, the University of the Free State and the University of Venda (formerly University of Limpopo). This assessment represents a pioneering effort in applying IUCN Red List criteria to a mega-diverse invertebrate group. It was made possible through the 22-year South African National Survey of Arachnida (SANSA) initiative, which resulted in significant improvements to the knowledge base: a 33% increase in described species and a 350% rise in specimen accessions in the ARC's National Collection of Arachnida (NCA). See details about how the IUCN Red List assessments are conducted [here](../integrated-findings/chl_rls_explained.qmd)\n\n**Data sources and methods**\n\nThe assessment utilised data from the First Atlas of South African Spiders [@a2010a], which compiled information from two primary sources: the National Collection of Arachnida (NCA) at the Agricultural Research Council – Plant Health and Protection (ARC-PHP) in Roodeplaat, Pretoria (with over 60 000 records) and published taxonomic literature from 17 museum collections.\n\nThe distribution of occurrence records across South Africa, Lesotho and Eswatini was visualised using quarter-degree, degree-square and density kernel plots for all 76 069 records. However, records in the NCA that were not identified to species level were excluded from the Red List assessments, reducing the analytical dataset to 23 827 species-level records covering 2 253 known South African spider species.\n\n**Calculation of parameters**\n\nThe calculation of Red List parameters was performed using the R package red (v1.6.3) [@cardoso2017a]. Spatial analyses on observed occurrences used functions for calculating Extent of Occurrence (EOO), Area of Occupancy (AOO), and elevational range. EOO was calculated as the minimum convex polygon around all occurrences, while AOO was determined by the number of 2 km² cells occupied. When EOOs were smaller than the AOO, they were made equal. Assessments were drafted as per the IUCN documentation standards and reviewed by relevant experts.\n\n**Assessment criteria and limitations**\n\nAll Red List assessments relied exclusively on IUCN criteria B (geographic range) or D (population size), as these could be evaluated from available distribution data and inferred threats. The other IUCN criteria (A, C, and E) require empirical evidence of population dynamics and trends – a critical data gap known as the Prestonian shortfall – which remains unavailable for most spider species. This methodological constraint highlights the need for long-term monitoring programs to provide insights into population dynamics.\n\n## Acknowledgements\n\nThe first IUCN Red List assessment of South African spiders was conducted between 2016 and 2019, as a collaborative project between the South African National Biodiversity Institute (SANBI), the Agricultural Research Council (ARC), the University of the Free State, National Museum Bloemfontein, and the University of Venda (formerly University of Limpopo), with the National Research Foundation (NRF) providing funding and support. South African National Parks and E. Oppenheimer & Son support and provide opportunities to collect in the parks and reserves and the provincial conservation agencies for collecting permits.\n\n:::::: grid\n::: {.g-col-lg-4 .g-col-12}\n**Coordinated by:**\n\n------------------------------------------------------------------------\n\n-   [South African National Biodiversity Institute](https://www.sanbi.org/)\n\n-   [Agricultural Research Council](https://www.arc.agric.za/)\n\n-   [University of Free State](https://www.ufs.ac.za/)\n\n-   [National Museum Bloemfontein](https://nationalmuseum.co.za/)\n\n-   [University of Venda](https://www.univen.ac.za/)\n:::\n\n::: {.g-col-lg-4 .g-col-12}\n**Sponsored by:**\n\n------------------------------------------------------------------------\n\n-   [National Research Foundation](https://www.nrf.ac.za/)\n:::\n\n::: {.g-col-lg-4 .g-col-12}\n**Supported by:**\n\n------------------------------------------------------------------------\n\n-   [South African National Parks](https://www.sanparks.org/)\n\n-   [E. Oppenheimer & Son](https://www.privateequityinternational.com/institution-profiles/e-oppenheimer-son.html)\n\n-   Provincial conservation agencies\n:::\n::::::\n\n### Contributors\n\n\n::: {#tbl-2 .cell .plain tbl-cap='List of contributors mobilising IUCN Red List assessments and support with field work during SANSA and museum staff.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xnyvumyyne\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xnyvumyyne table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xnyvumyyne thead, #xnyvumyyne tbody, #xnyvumyyne tfoot, #xnyvumyyne tr, #xnyvumyyne td, #xnyvumyyne th {\n  border-style: none;\n}\n\n#xnyvumyyne p {\n  margin: 0;\n  padding: 0;\n}\n\n#xnyvumyyne .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 12px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xnyvumyyne .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xnyvumyyne .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xnyvumyyne .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xnyvumyyne .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xnyvumyyne .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xnyvumyyne .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xnyvumyyne .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xnyvumyyne .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xnyvumyyne .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xnyvumyyne .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xnyvumyyne .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xnyvumyyne .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xnyvumyyne .gt_row {\n  padding-top: 12px;\n  padding-bottom: 12px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xnyvumyyne .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnyvumyyne .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xnyvumyyne .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xnyvumyyne .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xnyvumyyne .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnyvumyyne .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xnyvumyyne .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnyvumyyne .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xnyvumyyne .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnyvumyyne .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xnyvumyyne .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnyvumyyne .gt_left {\n  text-align: left;\n}\n\n#xnyvumyyne .gt_center {\n  text-align: center;\n}\n\n#xnyvumyyne .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xnyvumyyne .gt_font_normal {\n  font-weight: normal;\n}\n\n#xnyvumyyne .gt_font_bold {\n  font-weight: bold;\n}\n\n#xnyvumyyne .gt_font_italic {\n  font-style: italic;\n}\n\n#xnyvumyyne .gt_super {\n  font-size: 65%;\n}\n\n#xnyvumyyne .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xnyvumyyne .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xnyvumyyne .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xnyvumyyne .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xnyvumyyne .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xnyvumyyne .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xnyvumyyne .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xnyvumyyne .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xnyvumyyne div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: left;\" scope=\"col\" id=\"Contributor\">Contributor</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #D1D3D4; border-top-width: 2px; border-top-style: solid; border-top-color: black; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 0px; border-left-style: hidden; border-left-color: NA; border-right-width: 0px; border-right-style: hidden; border-right-color: NA; font-weight: bold; text-align: left;\" scope=\"col\" id=\"Affiliation\">Affiliation</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Annette van den Berg</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Agricultural Research Council</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Astri Leroy</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Spider Club of Southern Africa</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Colin Schoeman</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">University of Venda</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Connie Anderson</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Agricultural Research Council</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Esethu Nkibi </td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">South African National Biodiversity Institute</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Eugene Modiseng</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Agricultural Research Council</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Keenan Meissenheimer </td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">South African National Biodiversity Institute</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Mohale Mokoena</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">South African National Biodiversity Institute</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Norbert Hahn</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">University of Venda</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Petro Marais</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Agricultural Research Council</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Reginald Christiaan</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">South African National Biodiversity Institute</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Robin Lyle</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Agricultural Research Council</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Ruan Booysen</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">University of Free State</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Sma Chiloane </td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Agricultural Research Council</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Carol Poole</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: gray50; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">South African National Biodiversity Institute</td></tr>\n    <tr><td headers=\"Contributor\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">Anisha Dayaram</td>\n<td headers=\"Affiliation\" class=\"gt_row gt_left\" style=\"text-align: left; border-top-width: 1px; border-top-style: dotted; border-top-color: gray50; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: black; border-left-width: 1px; border-left-style: solid; border-left-color: transparent; border-right-width: 1px; border-right-style: solid; border-right-color: transparent;\">South African National Biodiversity Institute</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Recommended citation\n\nDippenaar-Schoeman, A., Lyle, R., Raimondo, D.C., Sethusa, T., Foord, S., Haddad, C., Lotz, L., Hendricks, S.E., Monyeki, M.S., & Van Der Colff, D. 2025. Spiders. National Biodiversity Assessment 2025. South African National Biodiversity Institute. http://nba.sanbi.org.za/.\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "sp_spiders_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}