---
title: "Species trends - Red List Index"
subtitle:  "Integrated findings"
title-block-banner: "#adb5bd"
title-block-banner-color: white
---

The trend in species status over time was measured using the globally recognised indicator, the IUCN Red List Index of species (RLI). The RLI is calculated for specific taxonomic groups based on genuine changes in Red List categories over time. The RLI value ranges from 0 to 1 and, the lower the value, the faster the taxonomic group is heading towards extinction, i.e., if the value is 1, all taxa are Least Concern and if the value is 0, all taxa are extinct. The RLI is calculated only for comprehensively assessed taxonomic groups or groups where a representative sample has been selected. Changes in status over time has been tracked for 13 taxonomic groups (@fig-rli).

![The Red List Index (RLI) for taxonomic groups assessed in South Africa. The slope of the line indicates the rate at which species within each taxonomic group are becoming more threatened over time, e.g., note the sharp decline in sharks, birds, mammals and plants. The lower the value, the faster the group of species is heading towards extinction (if the value is 0, all species are extinct). The newly assessed group Anostraca (fairy shrimps) are threatened by degradation to ephemeral wetlands. \*Due to the extremely high number of plant species occurring in South Africa, the protection level is calculated for a statistically representative sample of 900 plant taxa.](imgs/rli11.png){#fig-rli fig-align="center" width="600"}

Increases in extinction risk is evident for most groups, but a marked increase in rate of extinction since the last assessment is evident from the change in angle of declines for reptiles, birds, mammals and plants (@fig-rli). Increases in threat status for birds has largely been due to freshwater birds impacted by increasing levels of pollution and other forms of habitat degradation, while the main drivers of declines for mammals, plants and reptiles have been climate change and loss of habitat for mining and renewable energy developments. Most plants that have been uplisted due to increasing levels of extinction risk are found in the Northern Cape (@fig-sp-heat). The province was severely impacted by the drought over the past decade, and is experiencing ongoing pressure from mining and renewable energy developments. The two groups at highest risk of extinction are freshwater fishes and cartilaginous fishes. Sharks, rays and chimaeras are included on South Africa’s RLI for the first time, with the majority having wide ranges that extend outside South African territory. Many of these cartilaginous fishes are long-lived, have slow growth and low reproductive output, and many are declining across their ranges due to overfishing (including from recreational fisheries and as bycatch from industrial fisheries), lethal bather protection measures and habitat degradation. Half of South Africa’s freshwater fishes are endemic, with many concentrated in Western Cape river systems. While only due for reassessment in 2026, the declining status of rivers and dwindling resources available for management actions where many of these species are concentrated likely means that they will continue on a declining trajectory.

![The density of species (per km2) that have increased in threat status since NBA 2018, for plants (A), terrestrial and freshwater animals (B) and marine animals (including sharks, sparids and marine birds only)(C). Plants in the Northern Cape’s Namaqualand region are under the most severe pressure from climate change related drought, mining and succulent poaching, while the impacts on terrestrial and freshwater animals are widespread but linked to areas with high habitat loss and degradation. In the marine realm, increased risk to species is attributed to multiple pressures with coastal mining, estuarine degradation, flow reduction, overfishing and lethal shark control measures contributing to worsening species threat status.](imgs/sp-heatmap12.png){#fig-sp-heat fig-align="center" width="800"}
