{
  "hash": "5eaf63f88ae477e699fd6156dbd8c430",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Overview\"\nsubtitle: \"Marine realm\"\ntitle-block-banner: \"#02268A\" #imgs/overview_banner.jpg #\ntitle-block-banner-color: white\nimage: imgs/card_mar_Eve_Marshall.png\ndescription: | \n  Findings of the NBA presented by realm\n---\n\n\n\n*South Africa has exceptional marine biodiversity with 163 marine ecosystem types and high marine endemism linked to the intersection of three oceans and two contrasting current systems that interact with a diverse topographic and geological setting. Our marine biodiversity underpins food and job security, an expanding ocean economy, and is integral to the deep cultural and spiritual values held by many South Africans. The 2025 National Biodiversity Assessment identified marine ecosystems, species and benefits at risk, identified knowledge gaps that limit the assessment, and identified priority areas, together with co-developed priority actions, to safeguard ocean life, livelihoods and maintain the many benefits of South Africa’s rich marine biodiversity.*\n\n![South Africa's seascape harbours rich biodiversity with many benefits to society. (© Peter Chadwick)](imgs/009_Table_Mountain_PeterChadwick_AfricanConservationPhotographer.png){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n::::: columns\n::: {.column width=\"50%\"}\n<center>\n\n| [45%]{.inline-style-threatened}\n| of 163 ecosystem types\n| [Threatened]{.inline-style-indicator}\n\n| [20%]{.inline-style-well-protected}\n| of 163 ecosystem types\n| [Well Protected]{.inline-style-indicator}\n\n</center>\n:::\n\n::: {.column width=\"50%\"}\n<center>\n\n| [17%]{.inline-style-not-protected}\n| of 163 ecosystem types\n| [Not Protected]{.inline-style-indicator}\n\n| [36%]{.inline-style-threatened}\n| of 495 taxa assessed\n| [Threatened]{.inline-style-indicator}\n\n</center>\n:::\n:::::\n\n------------------------------------------------------------------------\n\n<!-- \\ to create an empty line (space) -->\n\n\\\n\n<!--# Follow the summary section with a relevant picture. Convert pictures to .png or .webp format, with a maximum 800px width, and 72 DPI for web resolution. Store all images in a folder called imgs. Insert images using visual editor Insert -> Figure/Image. Add a descriptive caption in the caption box. Set image alignment to center -->\n\n<!-- ![Caption to be added](imgs/Marine_Biodiveristy_Assessment.jpg){fig-align=\"center\"} -->\n\n## Ecosystem assessments\n\nOf South Africa’s 163 marine ecosystem types, [45% are threatened](marine_ets.qmd), particularly smaller ecosystem types of restricted distribution. Several small, high-value ecosystem types are at risk of ecosystem collapse, which could compromise food and job security and climate resilience (key message [A2](../key-messages/kma2.qmd)).\n\nOverall, coastal and shelf ecosystems are at higher risk of ecosystem collapse, and the most threatened ecosystem functional groups are bays, deepwater biogenic beds, muddy shelves and rocky ecosystems on the shelf. Unless collaborative efforts are made to improve ecological condition in these functional groups, the vital ecosystem services and benefits they provide are at risk (key message [A2](../key-messages/kma2.qmd)).\n\nMore than 80% of South Africa's 163 marine ecosystem types now have some representation in the Marine Protected Area (MPA) network, but only 20% are Well Protected (key message [B4](../key-messages/kmb4.qmd)). Slopes, abyssal plains, muddy and rocky shelves, and open oceans are the most Poorly Protected ecosystem functional groups.\n\nIncreasing the extent of South Africa’s MPA estate will contribute to improving ecosystem protection levels. For certain ecosystem types to advance to Well Protected status, however, their ecological condition inside MPAs needs improvement (key message [C2](../key-messages/kmc2.qmd)). Ocean governance needs to better consider and involve human dimensions in conservation initiatives (key message [C1](../key-messages/kmc1.qmd)), diversify protection models, and address persistent challenges that undermine the legitimacy of conservation areas.\n\nIn the marine realm, 17% of ecosystem types are both highly threatened and under protected. These ecosystem types are found on the West Coast, the western Agulhas Bank shelf edge, parts of the Agulhas Bank and parts of the KwaZulu-Natal Bight (see [intersection of ecosystem threat status and protection level](marine_ets_epl.qmd#fig-rle_map) page).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Map of the 163 marine ecosystem types in South Africa, including (A) 128 combined benthopelagic (shelf) and 22 deep-sea benthic (deep-sea) types and (B) 13 deep-sea pelagic types. The insert on A shows the transition between the Natal (warm colours) and Delagoa ecoregions (pink/purple colours). The map can be downloaded from [BGIS](https://bgis.sanbi.org/Projects/Detail/2246) and the key is available on the [ecosystem types](marine_ecosystems.qmd) page.](imgs/benthic_pelagic_map_panel.png){#fig-eco_map width=400}\n:::\n:::\n\n\n## Species assessments\n\nMarine species are assessed in terms of their [threat status and/or stock status](../species/marine_sp.qmd). Stock status refers to the resource status from a fisheries management perspective, whereas species threat status focuses on extinction risk using the [IUCN Red List of Threatened Species](https://www.iucnredlist.org/) criteria.\n\nOf the 495 marine species assessed using the [IUCN Red List of Threatened Species](https://www.iucnredlist.org/) criteria, [36% are considered threatened](../species/marine_sp.qmd) (key message [B1](../key-messages/kmb1.qmd)). However, this is an inflated estimate of the actual proportion of marine taxa that are threatened because species that are at risk and/or economically important have been prioritised for assessment, with few marine taxonomic groups being comprehensively assessed.\n\nThere is increasing knowledge on stock status of resources, with evidence of resource recovery for some species linked to improved fisheries and spatial management (key message [A5](../key-messages/kma5.qmd)). This shows that fish stocks can recover with effective collaborative management of effort, catch and area. However, some inshore resources are increasingly depleted, and South African abalone (*Haliotis midae*) and West Coast rock lobster (*Jasus lalandii*) are Endangered. Illegal fishing plays a key role in the Endangered status of these species (key message [A6](../key-messages/kma6.qmd)).\n\n![Several marine invertebrate resources, seabreams and shark and rays were assessed as threatened in 2025. West Coast rocklobster are Endangered (© Geoff Spiby); dageraad are Critically Endangered (© Steve Benjamin); bull sharks are Vulnerable (© Fiona Erst).](imgs/overview_species.png)\n\nSharks, rays and chimaeras are one of the most threatened groups across all realms (see [species status](../species/marine_sp.qmd) page). A re-assessment of South Africa’s seabreams showed improved threat status for three species while two have become more threatened. Of the 97 South African shallow reef building corals assessed globally, 37% are threatened by climate change (key message [A1](../key-messages/kma1.qmd)).\n\nMarine species continue to have the highest levels of data deficiency across all realms, signalling the need to address knowledge gaps, improve monitoring (key message [C3](../key-messages/kmc3.qmd)), and increase capacity for marine species red listing (key message [C3](../key-messages/kmc3.qmd)). High levels of data deficiency compromise effective species and ecosystem management, spatial planning, and decision-making.\n\n## Pressures and ecological condition\n\n::::: grid\n::: {.g-col-lg-8 .g-col-12}\nThere are many interacting pressures cumulatively affecting marine ecosystems and species. [Key pressures impacting marine biodiversity](marine_pressures.qmd) are fishing (including industrial, recreational and illegal fisheries), coastal development (including ports and harbours), pollution, shipping, mining, freshwater flow reduction, lethal shark control measures and climate change.\n\nFishing, petroleum activities and shipping are widespread sectors resulting in many pressures on multiple ecosystem components and species. Fishing, particularly industrial fishing, continues to exert the greatest pressures on marine biodiversity (key message [A5](../key-messages/kma5.qmd)) impacting ecosystems, species and genetic diversity (key message [B3](../key-messages/kmb3.qmd)).\n:::\n\n::: {.g-col-lg-4 .g-col-12}\n![Map of 31 cumulative pressures in South Africa's ocean. Red and orange areas represent the highest cumulative pressures, while blue areas represent low pressures. White areas contained no mapped pressures. Click image to expand.](imgs/cum_press_low_res.png){#fig-pressures .lightbox}\n:::\n:::::\n\nHotspots of degradation and cumulative impacts are often driven by the location of ports and harbours, which increase access for fishing, alter shorelines and current circulation, increase pollution, and facilitate the introduction and spread of invasive species. Pollution including industrial, municipal and noise pollution are key escalating pressures. Seismic surveys to detect potential offshore oil and gas resources have been expanding into deeper waters and, together with shipping and other sources of underwater noise, pose uncertain risks to marine ecosystems and species. Renewable energy production is important in achieving energy security and reducing climate change impacts but marine renewable energy development requires careful consideration of marine biodiversity impacts.\n\n::::: grid\n::: {.g-col-lg-8 .g-col-12}\nThe first groundtruthing of [marine ecosystem condition](marine_condition.qmd) shows that pressure mapping is an effective proxy at broad national scales, but that finer scale pressure mapping can improve condition estimates. However, despite their importance in spatial planning, most marine pressure data are outdated, leading to missing pressures, poor resolution of some pressures, and inaccuracy of pressure impacts on ecosystem condition. Increased monitoring is needed to support assessment of ecosystem and species (key message [B5](../key-messages/kmb5.qmd)), and to quantify ecological condition more accurately for both biodiversity assessment and guiding management.\n:::\n\n::: {.g-col-lg-4 .g-col-12}\n![Map of ecological condition showing the spatial distribution of marine areas in natural/near natural, moderately modified, heavily modified or severely modified state. Click image to expand.](imgs/condition.png){#fig-condition .lightbox}\n:::\n:::::\n\nThe impacts of cumulative pressures also warrant consideration at multiple scales, particularly in evaluating the impacts of expanding and diversifying ocean economy activities. Failure to account for indirect and cumulative impacts on biodiversity will mean that important impacts are missed, resulting in poor spatial planning and decisions, with negative impacts on people and the environment (key message [A2](../key-messages/kma2.qmd)).\n\n## Knowledge gaps, priority actions and priority areas\n\nThe NBA 2025 identified knowledge gaps limiting the assessment and research priorities that could strengthen biodiversity assessment, spatial and management planning, and enable decision-making underpinned by holistic science and diverse forms of knowledge.\n\nPriority actions for improving the state of marine biodiversity were co-developed in collaboration with knowledge holders, policy and decision makers through a series of science-policy-society dialogues. More than 80 actions were advanced and these were distilled into 10 overarching actions with proposed indicators against which progress can be tracked (see [knowledge gaps, priority actions and priority areas page](marine_priority_actions.qmd)).\n\nSpatial biodiversity priority areas to protect, restore and recover marine ecosystems and species have been identified and planning is being improved with increased participation, collaboration and technical innovation.\n\nDrawing from key findings of the NBA, ten priority actions were co-developed for improving the state of marine biodiversity. Each of these are associated with several potential indicators for progress. The priority actions include:\n\n-   Enable broader participation in ocean planning, assessment, management and governance. [Read more »](marine_priority_actions.qmd#box-4)\n\n-   Improve marine coordination within government and strengthen collaborations for improved ecosystem-based ocean management and decision-making. [Read more »](marine_priority_actions.qmd#box-5)\n\n-   Avoid, reduce and effectively manage industrial impacts to safeguard marine biodiversity and ecosystem services. [Read more »](marine_priority_actions.qmd#box-6)\n\n-   Ensure sufficient quantity and quality of freshwater flows to marine ecosystems. [Read more »](marine_priority_actions.qmd#box-7)\n\n-   Build on past successes to manage fisheries better and more fairly to improve ocean health and food and livelihood security. [Read more »](marine_priority_actions.qmd#box-8)\n\n-   Ensure that existing Marine Protected Areas (MPAs) function effectively, and expand and diversify South Africa’s conservation estate. [Read more »](marine_priority_actions.qmd#box-9)\n\n-   Update and advance spatial data and maps to strengthen marine biodiversity assessment, planning and management. [Read more »](marine_priority_actions.qmd#box-10)\n\n-   Ensure South Africa has the skills and infrastructure to manage and deliver expanding data for ocean planning and decision-making. [Read more »](marine_priority_actions.qmd#box-11)\n\n-   Maintain marine biodiversity benefits through improved statistics, communication and knowledge sharing. [Read more »](marine_priority_actions.qmd#box-12)\n\n-   Reduce climate risks to people and nature. [Read more »](marine_priority_actions.qmd#box-13)\n\n![Science-to-policy dialogue convened in November 2024 to co-develop priority management and policy actions for improving the state of South Africa's marine biodiversity for the benefit of nature and people. (© Kerry Sink)](imgs/workshop.png)\n\n<!-- ## Key publications -->\n\n<!-- Sink, K.J., van der Bank, M., Majiedt, P.A., Harris, L., Atkinson, L. & Karenyi, N., 2019. *National Biodiversity Assessment 2018: Technical Report Volume 4: Marine realm*. Pretoria: South African National Biodiversity Institute. -->\n\n## Acknowledgements\n\nThe NBA is produced by the South African National Biodiversity Institute (SANBI) as part of its mandate to report regularly to the Minister of Forestry, Fisheries and the Environment on the status of the country’s biodiversity. SANBI's way of working is highly collaborative, recognising that such a technically demanding and wide-ranging scientific assessment cannot be achieved without substantial support from numerous partners and collaborators. The Marine Realm Assessment was conducted in collaboration with 211 individuals (25% Early Career Ocean Professionals), across 61 institutions, spanning academia, government and public organisations, industry associations, NGOs, community based organisations, and independent individuals. This Marine Realm Assessment would not have been possible without the substantial in-kind contributions of time, data and expertise from these individuals and institutions. Over the past six years, this multitude of dedicated collaborators invested 26 292 person hours (over 14 yrs of work) to strengthen the knowledge based that underpins the NBA 2025 Marine Realm Assessment.\n\nWe sincerely thank the National Marine Ecosystem Committee and Network for their invaluable technical expertise and guidance. The National Marine Biodiversity Scientific Working Group is thanked for its role as reference group for the Marine Realm Assessment of the NBA. The National Working Group 7 (Oceans and Coasts) is thanked for it valuable inputs and contributions to the draft marine key messages. We also acknowledge members of the Biodiversity Planning Technical Working Group, the National Ecosystem Classification Committees, and the NBA Core Reference Group for their input.\n\nWe acknowledge the National Research Foundation for funding research that provided key inputs into the NBA especially projects funded through the Foundational Biodiversity Information Program (FBIP) and the African Coelacanth Ecosystem Program (ACEP). These include the SAEON led SeaMap project (Grant number 138572) and ACEP Deep Forests (Grant number 110765), Deep Connections (Grant number 129216), Agulhas Bank Connections (Grant number 129213) and Sound Seas projects (Ref number ACEP23040790163). International funding support was provided through the European Union's Horizon 2020 Research and Innovation Program under Grant Agreement No. 862428 (Mission Atlantic project) and 818123 (iAtlantic project), the German Federal Ministry for Economic Cooperation and Development (BMZ) through the Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH for the MeerWissen CoastWise project, and the UK Research and Innovation (UKRI) through the Global Challenges Research Fund (GCRF), Grant ref: NE/S008950/1, for the One Ocean Hub project.\n\n![](imgs/logo_cloud.jpg)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}