---
title: "NBA 2025 Key Messages"
subtitle: ""
title-block-banner: "#adb5bd"
title-block-banner-color: white
---

The **NBA 2025 Key messages** distill some of the most important findings of NBA 2025 in a way that is accessible to various audiences.

Each message includes a summary paragraph with a confidence statement. The messages draw on evidence from NBA analyses (e.g., Red List status, ecological condition), explain, **why this matters** (e.g., consequences for people), and point to **practical actions, responses, and interventions** that can be taken.

The NBA provides a **summary of the state of biodiversity at a point in time**. It cannot list every action or intervention; instead, it serves as a **strategic tool** that should stimulate discussions among stakeholders and inform sector specific strategies and action plans, cross-sectoral planning, research strategies, scenario planning, and co-produced response strategies that follow from the NBA.

## How to use these messages

-   Read each key message with its **underlying data** and analyses.

-   Use them to inform **sector strategies, cross-sector planning, research, scenario planning,** and **implementation roadmaps.**

-   Treat confidence statements as guidance on **certainty, evidence quality,** and **agreement.**

## CLUSTER A: Cross-realm pressures on South Africa's biodiversity are impacting people

This cluster highlights the key pressures on South Africa's biodiversity across realms, and how these pressures have impact on the numerous benefits people derive from biodiversity.

[A1. Accelerated climate change has widespread impacts on biodiversity and people](kma1.qmd)

[A2. Unsustainable land use and sea use changes erode natural capital and undermine ecosystem services](kma2.qmd)

[A3. Pollution reduces water quality, impacting aquatic ecosystems and their dependent economic activities](kma3.qmd)

[A4. The prevention and management of biological invasions remain a priority](kma4.qmd)

[A5. Building on past successes, opportunities exist for more sustainable and equitable fisheries](kma5.qmd)

[A6. Innovation is needed to address escalating illegal wildlife harvesting and trade](kma6.qmd)

[A7. Freshwater flows from land to sea are essential for coastal ecosystems, species and communities](kma7.qmd)

## CLUSTER B: Improving the status of South Africa's biodiversity is key to a sustainable and equitable future for all

This cluster relates to the status of South Africa's biodiversity, using national and international headline indicators. These messages encourage intensive effort towards ensuring a society living in harmony with nature, where biodiversity conservation and sustainable use ensure healthy ecosystems, with improved benefits that are fairly and equitably shared for present and future generations.

[B1. Recovery efforts are required to curb rising extinction risk and a growing number of threatened species](kmb1.qmd)

[B2. Estuaries, rivers and wetlands are the most threatened and least protected ecosystems in South Africa](kmb2.qmd)

[B3. Genetic diversity of South African indigenous species' populations is declining](kmb3.qmd)

[B4. Enhancing effectiveness of protected and conserved areas for mitigating pressures on biodiversity will build on progress in representing ecosystems and species](kmb4.qmd)

[B5. Scientific and well-documented programmes are needed for ecosystem restoration and species recovery](kmb5.qmd)

## CLUSTER C: Inclusive actions across the whole of government and whole of society are needed to secure nature's contributions to people

This cluster speaks to three all-inclusive and over-arching actions that are needed to accelerate the calls to action expressed in each message in cluster A and B.

[C1. Safeguarding South Africa's biodiversity calls for a whole-of-government and whole-of-society approach](kmc1.qmd)

[C2. Investment in biodiversity monitoring is crucial for management, decision-making, research and reporting](kmc2.qmd)

[C3. Innovative finance solutions are needed to address funding and capacity constraints in the biodiversity sector](kmc3.qmd)
