---
title: "A3. Pollution reduces water quality, impacting aquatic ecosystems and their dependent economic activities"
subtitle: ""
title-block-banner: "#FAA755"     
title-block-banner-color: white
---

**The negative impacts of pollution continue to increase in South Africa’s aquatic ecosystems, exceeding sustainable limits and affecting biodiversity, human wellbeing, and economic development (*established*). South Africa has advanced water policy, however, there is a need to strengthen compliance monitoring and enforcement for aquatic ecosystems.**

------------------------------------------------------------------------

![South Africa’s aquatic systems face multiple forms of pollution, including from plastics, pesticides, untreated wastewater, urban runoff and more. Their capacity to assimilate pollutants is being exceeded with consequences for biodiversity, health and economic development. This eutrophication is from sewage spillage into the river. (© Hlengiwe Mtshali)](imgs/19a.%20Pg26_KMA3_Bloubankspruit-Muddelsdrift-sewage%20spillage%20into%20a%20river_Hlengiwe%20Mtshali.png)

South Africa’s rivers, wetlands, groundwater, estuaries and marine ecosystems are vital for water and food security, yet are compromised by pollution that contributes to a third of aquatic ecosystem extent being in poor condition. Half of South Africa’s estuaries have moderate to very high levels of pollution. The pollution originates from point and non-point sources, including agricultural return flow, discharge from wastewater treatment works, sanitation distribution networks, unmanaged urban stormwater, and other production and industrial processes. Poor solid waste management, particularly from rural and peri-urban areas upstream or near to water resources, also impacts water quality. Pollution disrupts the functioning of terrestrial, freshwater and coastal ecosystems, compromising ecosystem services, causing eutrophication and oxygen depletion and local die-off of aquatic species, and often supporting uncontrolled spread of invasive aquatic plants. Emerging pollutants such as microplastics, persistent organic pollutants (e.g., PFAS[^1]) and pharmaceuticals threaten water safety and aquatic biodiversity. Recent studies have detected DDT[^2] and other organochlorine pesticides in Lake Sibaya, coral reefs and offshore marine ecosystems.

[^1]: *Polyfluoroalkyl substances represent a large class of synthetic chemicals used throughout society, sometimes called ‘forever chemicals’ due to their persistence in the environment and human body.*

[^2]: *Dichlorodiphenyltrichloroethane (DDT) usage was discontinued for agricultural use in South Africa in 1983, but is used for malaria control. In addition to posing health risks to people, DDT is persistent and bioaccumulates in ecosystems.*

South Africa’s aquatic ecosystems have limited pollution assimilation capacity, which is being exceeded. Contaminated water has public health implications and reduces the availability of clean drinking water, and water of suitable quality for food production and other economic activities. Toxins from pollution accumulate in food chains, affecting both aquatic life and the human communities that depend on ecosystems for food security and livelihoods. These impacts disproportionately affect the most vulnerable communities who are directly reliant on natural water sources.

South Africa needs to improve management of pollutants, particularly for wastewater, agricultural runoff, urban stormwater and emerging contaminants. With increased demand on water resources and considering the water-food-energy nexus, there is a need for alignment in policy, law and governance for integrated water quality management. Recent achievements include the publishing of the National Water Resource Strategy III in 2023, the South African Water Quality Guidelines for Coastal Marine Waters in 2022, and the Marine Pollution (Prevention of Pollution from Ships) Amendment Bill in 2025. These recent advances in water policy now require well-resourced action. It is vital to amplify current investment in modernising wastewater treatment works to ensure they meet current and future demands. Innovative urban drainage solutions should be instituted to improve stormwater management. Pollution levels in aquatic ecosystems should be effectively monitored. Water pollution is a complex developmental, economic, social, and environmental issue. Addressing it effectively requires an integrated, participatory approach and collaborative partnerships across all levels of society, including government, the private sector and civil society. 
