---
title: "A7. Freshwater flows from land to sea are essential for coastal ecosystems, species and communities"
subtitle: ""
title-block-banner: "#FAA755"
title-block-banner-color: white
---

**Sufficient flow of clean water from land to sea is important for the functioning of coastal, estuarine and marine ecosystems, with implications for water quality, marine fisheries and coastal resilience to disasters (*established*). Sustaining the vital flow of freshwater to the sea requires an integrated approach that combines the management of flow, water quality and ecological and built infrastructure with coordinated efforts across all components.**

------------------------------------------------------------------------

Freshwater flows into the ocean are essential for functioning coastal and marine ecosystems and the species that live in them. Estuaries demonstrate this interconnectivity between land and sea, and more than 20% suffer severely reduced freshwater flow and 32% are under severe pollution pressure. Flow reduction and poor water quality cause poor coastal ecosystem condition and increased species threat in the estuarine and marine realms. South Africa has very few (only 62) remaining free-flowing rivers that reach the coast without substantial barriers limiting flows and species movement. The water from many of the country’s catchments is already fully allocated for human uses inland, leaving ever decreasing volumes to flow into the ocean.  

![Freshwater reaching the sea is not wasted. Sediment-rich clean water, flowing from catchments through estuaries into the ocean, is essential and provides multiple benefits such as nutrients for fish and sand for beaches and dunes (© Darren Hanner). Actions have been identified to track progress in securing freshwater flow to the estuarine and marine realms.](imgs/25.%20Pg30_KMA7_20190329_074018_sediment_(c)Darren%20Hanner.png)

Sufficient freshwater flow into the ocean maintains water quality, salinity regimes, and estuarine connectivity that supports fish nursery functions vital for marine fisheries. Freshwater flow enables the movement of sand and sediments, maintaining beaches and dunes, which are tourism and coastal resilience assets that help protect people from sea storms. Fisheries associated with muddy ecosystem types (e.g., prawns, sole) require mud delivery through freshwater flows to the sea. Species that move between marine and freshwater environments during their life cycle (e.g., eels \[*Anguilla* spp.\] and the commercially-important dusky kob \[*Argyrosomus japonicus*\]) are particularly vulnerable when estuarine connectivity and functioning are altered. 

Ecological infrastructure, such as catchments, rivers and wetlands, together with built infrastructure, facilitates and regulates freshwater flows into the sea. A lead agency is needed to coordinate the development of an officially accepted standard protocol for the determination and implementation of flow requirements for fluvial-dependent marine ecosystems and resources. Then, alignment of strategies amongst stakeholders, such as the National Water Resources Strategy and Water Resource Classification, can ensure that flow requirements are implemented. Coordinated monitoring, data management and sharing will further support this effort. Investing in water resource monitoring and reporting is crucial to understand trends in streamflow quality and quantity, including associated declining estuary and coastal ecosystem conditions. Natural capital accounting, including the subnational water resource accounts and Strategic Water Source Areas accounts provides insights into how water moves across the landscape. Catchment Management Agencies play a key role by encouraging partnerships across sectors for collaborative water governance. Finally, coastal and estuary management plans must detail freshwater allocation, fish resource use, water quality management and appropriate land-use activities.  
