---
title: "B1. Recovery efforts are required to curb rising extinction risk and a growing number of threatened species"
subtitle: ""
title-block-banner: "#70B276"
title-block-banner-color: white
---

**South Africa has recorded a marked rise in extinction risk for species over the past decade, with the international headline indicator, the Red List Index of species, showing accelerating declines (*established*). A whole-of-society approach is required for recovery efforts to meet national and international responsibilities.**

------------------------------------------------------------------------

South Africa’s most threatened taxonomic groups are freshwater fishes, cartilaginous fishes (sharks, rays and chimaeras) and succulent plants. Up to 66% of freshwater fish taxa are threatened, due to invasive alien fish and habitat modification. Other plants, reptiles, birds and mammals are also showing increased rates of decline over the past decade. More than 100 species have moved from Least Concern to threatened categories on the IUCN Red List of Threatened Species since 2018. The main cause has been population reductions linked to climate change (see key message A1) in the western parts of the country impacted by severe drought. The worst impacted region is northern Namaqualand, where endemic plants, beach macrofauna and reptiles have also experienced declines as a result of expanding mining activities. The increase in illegal trade has caused severe declines to species in use (see key message A6), including endemic plants, some marine invertebrates and cartilaginous fishes. Estuarine degradation, fishing and lethal shark control measures contribute to the threat status of cartilaginous fishes. Their decline is a global trend, yet with several endemic species, South Africa has a responsibility to protect them.

::: {layout-ncol="2"}
![Both largetooth sawfish (*Pristis pristis*) and green sawfish (*P.  zijsron*), were once common along the KwaZulu-Natal coast and in estuaries, but are now considered Critically Endangered within our waters (© Dennis King). Building on progress, South Africa can further diversify and modernise shark management measures to improve marine species status without unduly increasing risks to bathers.](imgs/26.%20Pg31_KMB1_Smalltooth%20sawfish%201%20DRK%20A%20(c)%20Dennis%20King.png)

![At least 55 plant species endemic to the Richtersveld region have been uplisted to highly threatened categories since NBA 2018 due to the combined impacts of climate change and rapidly expanding mining activities. All three species of tree aloes found in the Richtersveld, including this quivertree (*Aloidendron dichotomum*, Vunerable), were listed on the IUCN Red List of Threatened Species in 2022 as threatened as a result of population declines due to climate change. (© Wendy Foden)](imgs/27.%20Pg31_KMB1_DSC_0272%20(1)%20(c)%20Wendy%20Foden.png)
:::

The threatened status of several nearshore marine species is of concern for food and livelihood security (see key message A5), as is the status of other species harvested for food and medicine. Species support crop agriculture, the wildlife economy, tourism and many other jobs. South Africa is a megadiverse nation and has committed to global efforts to address the species extinction crisis. Target 4 of the Kunming-Montreal Global Biodiversity Framework calls for a concerted effort to halt human induced extinction of threatened species and for the recovery and conservation of species.

South Africa has many conservation tools available for species recovery. Sufficient resourcing is required to ensure Red List assessments are conducted and updated for all taxonomic groups at least every 10 years. Additional species information needs to be included in the National Environmental Screening Tool, particularly for the marine realm, and in Spatial Development Frameworks and Integrated Development Plans. In cases where species have experienced extreme losses and recovery is required, multiple partners need to work together. South Africa's Centre for Species Survival and the IUCN National Species Specialist Group have developed and costed recovery plans that estimate a 10-fold increase in spending on species recovery is required for South Africa to meet its obligation under the Kunming-Montreal Global Biodiversity Framework. Expanding protected and conserved areas and improving their effectiveness for under protected and threatened species remains crucial to safeguard South Africa's rich species diversity (See key message B4).
