---
title: "B4. Enhancing effectiveness of protected and conserved areas for mitigating pressures on biodiversity will build on progress in representing ecosystems and species"
subtitle: ""
title-block-banner: "#70B276"
title-block-banner-color: white
---

**South Africa has made progress towards expanding protected areas to be more ecologically representative of ecosystems and species (*well established*). Spatial biodiversity planning tools continue to guide strategic expansion efforts. By enabling better participation in conservation and restoration, addressing gaps in sustainable finance and enhancing effectiveness of protected and conserved areas, pressures on ecosystems and species can be further mitigated.**

------------------------------------------------------------------------

![South Africa has committed to expanding protected and conserved areas, to meet national and global goals. Realising this ambition will require strengthened community participation in establishing and managing these areas. Areas such as Gompo’s Rock (near East London, Eastern Cape) (© Kerry Sink), which hold both cultural and biodiversity significance could be explored for conservation and recognition as other effective area-based conservation measures (OECMs) in partnership with value holders.](imgs/30.%20Pg34_KMB4_Gompos%20Rock_Kerry%20Sink.png)

Expanding the ecological representation of ecosystems and species in protected and conserved areas strengthens their effectiveness in reducing pressures on biodiversity. South Africa has made progress in expanding protected and conserved areas, with spatial planning guiding the inclusion of diverse terrestrial, freshwater, estuarine, and marine ecosystems and their species. For example, the marine protected area network is spatially efficient and represents 83% of marine ecosystem types across 5.4% of South Africa’s ocean. Despite these advances, gaps remain in achieving fully representative coverage, particularly for estuarine and freshwater ecosystem types. Restoration initiatives, including controlling invasive species, could also increase effectiveness of these areas in protecting ecosystems and species. However, resources and capacity for management have not increased alongside the expansion of protected and conserved areas. 

Protected and conserved areas provide multiple benefits, including supporting sustainable jobs in tourism and the biodiversity economy, enhancing cultural and recreational experiences, and contributing to climate resilience and human wellbeing. Effective management of existing protected and conserved areas will ensure that progress made in expansion of these areas continues to deliver these benefits. Target 3 of the Global Biodiversity Framework calls for the conservation of 30% of land, waters and seas by 2030 at the global level, with attention to effectiveness, ecological representativity and equitable governance systems. South Africa, with innovative resourcing strategies (see key message C3), is committed to all elements of the target. 

Protected and conserved areas work well with community involvement. Diversified protection models and other effective area-based conservation measures (OECMs), can provide new opportunities for community-led conservation, livelihood diversification and cultural heritage protection. Initiatives that provide opportunities for communities living in and around protected and conserved areas to become active participants should be enhanced and encouraged. Combining aspects of both natural and cultural heritage in protected area expansion can foster the involvement of indigenous and local communities. Inclusive and participatory stakeholder processes are needed for more effective protected areas that support thriving people and nature. The biodiversity sector must strengthen capacity for social processes across institutions to create innovative partnerships with community and industry. Securing sustainable finance, enhancing institutional capacity, and fostering innovative partnerships with communities and industry are essential to ensuring that protected and conserved areas continue to deliver long-term ecological, social and economic benefits. 
