---
title: "B5. Scientific and well-documented programmes are needed for ecosystem restoration and species recovery"
subtitle: ""
title-block-banner: "#70B276"
title-block-banner-color: white
---

**Nature’s contributions to people are at risk due to poor ecological condition of ecosystems and pressures on important species (*established*). Restoration and recovery programmes, that are guided by science, implemented collaboratively and properly monitored are essential to ensure lasting benefits for both people and nature*.***

------------------------------------------------------------------------

![It is vital that ecosystem restoration and species recovery programmes are designed scientifically, and then evaluated for their effectiveness so that future programmes are cost-effective and have the best possible results for people and biodiversity. Species recovery projects may involve costly translocation efforts – here some leopards are checked before their relocation. (© North West Department of Economic Development, Environment, Conservation & Tourism)](imgs/31b.%20Pg35_KMB5_18_NW_(c)DEDECT_Immobilised%20leopards%20examined%20before%20relocated.png)

More than half of South African ecosystems are in poor ecological condition. A particularly high proportion of wetland (51%), river (75%), estuarine (82%) and coastal (48%) ecosystem extent is Moderately to Critically Modified. Species also suffer from multiple pressures, including unsustainable use, poaching or other impacts from human activities (e.g., pollution).

Often, the ecosystems and species that are most useful to people are those whose condition deteriorates the most. Wetland and river ecosystems provide people with essential water, and estuarine and coastal ecosystems are widely used for recreation, fishing and settlements. These ecosystems begin to lose their ability to provide these vital services as their condition deteriorates. In the same way, species that are used for harvesting or trade are susceptible to unsustainable use that threatens the resource. The Kunming-Montreal Global Biodiversity Framework (Target 2) calls for 30% of degraded ecosystems to be under effective restoration by 2030 in order to enhance ecological integrity and recover the benefits people receive from ecosystems. Target 4 calls for the recovery and conservation of species, in particular threatened species. The United Nations Convention to Combat Desertification also sets targets to avoid and slow degradation, and restore degraded lands to a natural, productive state (also part of the Sustainable Development Goals).  

Preventing species decline or ecosystem degradation should always be the primary focus. However, species recovery and ecosystem restoration programmes can be effective interventions when done in a responsible and scientifically sound manner. Prioritising where such initiatives should occur can ensure cost-effectiveness and lasting positive impacts for both people and biodiversity. Several recent initiatives focus on using spatial biodiversity data to scientifically plan restoration initiatives. For example, the National Coastal and Marine Spatial Biodiversity Plan has been used to identify strategic priorities for restoration in coastal and marine ecosystems, and South Africa’s Essential Life Support Action Areas map identified areas that should be prioritised for restoration on land. These efforts reiterate the value of spatial biodiversity information, such as the NBA threat status and protection level analyses, in supporting national priorities and actions. Species recovery initiatives should be equally well planned, as it is estimated that investments exceeding R1 billion are needed over the next five years to recover species under severe threat in South Africa (see key message B1). Monitoring and evaluating (see key message C2) of ecosystem restoration and species recovery interventions is crucial yet often neglected. Counterfactual impact evaluation and a national information system for restoration and recovery programmes are both essential for adaptive management, improving future projects and reporting meaningfully. Restoration and recovery should always be a collaborative effort, involving indigenous knowledge and a whole-of-society approach to future-proof programmes with diverse stakeholder expertise. 
