---
# indentations are critical in YAML headers, be careful when editing this section

title: "Priority actions and research" 
subtitle: "Coastal zone" 

title-block-banner: "#DEA004" #Background colour of the title block: Apply component colours where necessary - find hex codes in _brand.yml
title-block-banner-color: white # Header text colour: DO NOT CHANGE

# List authors here in the order you want them displayed in the title block
# See examples in README
author:
  # Copy this block and add details for each author of your page. Make sure you maintain indentations exactly as they are here
  - name:
      given: Linda R. #Add author's first name here. Abbreviate the middle name
      family: Harris #Add author's surname here
    orcid: 0000-0003-4719-0481 # Author's orcid ID. Delete this line if author is not on orcid
    affiliations:
      - ref: nmu 
  - name:
      given: Kerry J. #Add author's first name here. Abbreviate the middle name
      family: Sink #Add author's surname here
    orcid: 0000-0001-5051-573X # Author's orcid ID. Delete this line if author is not on orcid
    affiliations:
      - ref: sanbi
      - ref: nmu
  - name:
      given: Andrew L. #Add author's first name here. Abbreviate the middle name
      family: Skowno #Add author's surname here
    orcid: 0000-0002-2726-7886 # Author's orcid ID. Delete this line if author is not on orcid
    affiliations:
      - ref: sanbi
      - ref: uct
  - name:
      given: Lara #Add author's first name here. Abbreviate the middle name
      family: Van Niekerk #Add author's surname here
    orcid: 0000-0001-5761-1337 # Author's orcid ID. Delete this line if author is not on orcid
    affiliations:
      - ref: csir
      - ref: nmu

affiliations:
# List affiliations here and number them in the order that they are associated with the list of authors above. If multiple authors have the same affiliation, only list the affiliation once here.
# Write out institutional names in full
# See README for common examples - they can be copied and pasted here
# Make sure you maintain indentations exactly as they are here
  - id: nmu # Use this as the affiliation ref with authors above
    number: 1 # This number is used to associate authors with affiliations
    name: Nelson Mandela University
  - id: sanbi # Use this as the affiliation ref with authors above
    number: 2 # This number is used to associate authors with affiliations
    name: South African National Biodiversity Institute
  - id: uct # Use this as the affiliation ref with authors above
    number: 3 # This number is used to associate authors with affiliations
    name: University of Cape Town
  - id: csir # Use this as the affiliation ref with authors above
    number: 4 # This number is used to associate authors with affiliations
    name: Council for Scientific and Industrial Research

# This date determines the PUBLISHED date in the title block
date: last-modified

# Remember to rename the default .bib file and change the name here
bibliography: cst_references.bib

# This section sets up the page citation format. DO NOT EDIT
citation:
  type: webpage
  container-title: National Biodiversity Assessment 2025
  publisher: South African National Biodiversity Institute
  url: http://nba.sanbi.org.za/
# Do not edit or change any of the following entries
appendix-cite-as: false
google-scholar: true
---

------------------------------------------------------------------------

## Priority actions

<!--# I haven't invested a lot in this page because I don't know how this section will play out for the realms. This is the NBA 2018 content. -->

In addition to the overall priority actions distilled from this assessment<!--# inset link to overall priority actions/responses page -->, the 10 priority actions specifically for South Africa's coastal zone are:

**1. Restore the coast**

Restore and maintain coastal ecological infrastructure as part of a national coastal restoration plan to strengthen climate resilience and sustain ecosystem services and key benefits to South Africans.

**2. Diversify and create more jobs**

Diversify and create more job opportunities for coastal communities from tourism and coastal restoration and monitoring programmes to supplement livelihoods.

**3. Ensure sufficient quantity and improve the quality of freshwater flows to the coast**

Ensure sufficient freshwater flows through estuaries to the coastal and offshore marine environments, and improve coastal water quality by addressing pollution, particularly in priority areas, all to maintain healthy biodiversity assets and associated benefits.

**4. Re-establish flows of sand to beaches and dunes**

Re-establish natural sand supplies to the coast, where possible, to replenish sand-starved beaches and dunes and thereby maintain benefits of coastal protection, sustain South Africa’s most important biodiversity asset for tourism, and safeguard our unique beach biodiversity.

**5. Improve management to rebuild depleted stocks of coastal resources**

Improve management of current activities that use coastal natural resources to support rebuilding depleted stocks for long-term sustainability.

**6. Reduce mining impacts**

Reduce the impacts of mining by stopping illegal mining, avoiding biodiversity priority areas, and improving rehabilitation.

**7. Locate ports and harbours carefully**

Locate new ports and harbours appropriately through careful cross-sectoral planning to avoid widespread degradation of biodiversity priority areas and related benefits from the cumulative impacts associated with better ocean access.

**8. Use the National Coastal and Marine Spatial Biodiversity Plan to ‘close the gap’**

Use the National Coastal and Marine Spatial Biodiversity Plan (CBA Map and associated land- and sea-use guidelines) to align governance, planning and decision-making across realms and across organs of state to achieve effective, science-based and proactive integrated coastal zone management.

**9. Effectively communicate the benefits of coastal biodiversity**

Effectively communicate the value of South Africa’s coastal biodiversity through improved coordinated messaging that articulates benefits to build support for coastal conservation and mobilise people to sustainably use coastal biodiversity.

**10. Address knowledge gaps**

Catalyse research to address critical knowledge gaps that limit the assessment of coastal biodiversity and decision making for sustainable use and safeguarding the benefits of coastal biodiversity assets, especially in the face of global change.

## Knowledge gaps and research priorities

Nineteen knowledge gaps have been identified as research priorities to strengthen further coastal biodiversity foundational knowledge and understanding of impacts to coastal biodiversity to improve assessment, and also to better understand the benefits of biodiversity and the best ways of communicating the these in a way that most inspires South African’s into action for change towards long-term sustainability. These 19 knowledge gap–research priority clusters are grouped under four themes:

<details>

<summary>**Foundational data and knowledge**</summary>

**1. Advance the map of coastal ecosystem types**

-   Improve the rocky shore classification by advancing the wave exposure mapping from an expert-based layer to one underpinned by quantitative analysis.

-   Revisit the classification and mapping of mixed shore ecosystem types.

-   Complete the current, unpublished work on beach biogeography to confirm whether the tropical biogeographic break matches with that for estuaries and rocky shores, or whether it is indeed further north.

-   Improve mapping of estuary plumes (sediment-laden water) and fluvial fans (accumulations of terrigenous sediment on the seabed) to support delineation of river-influenced ecosystem types.

-   Improve classification and mapping of boulder and cobble shores.

-   Revisit how micobialites are represented in the map of ecosystem types.

-   Verify the inland extent of the ecologically determined coastal zone.

-   Revisit the classification of seashore vegetation types to determine whether the dune sub-types should be classified and assessed per each of four seashore types, or if some of the sub-types need to be elevated to the level of a separate seashore vegetation type.

-   Revisit the classification of inland wetlands to determine whether there are those that should be classified as coastal and included in the ecologically determined coastal zone.

**2. Improve taxonomic knowledge; map and assess coastal species**

-   Improve taxonomic knowledge, species distribution mapping and Red Listing of species.

-   Undertake more recent surveys on which to base some of the ecosystem assessments (e.g., Estuarine Health Index).

**3. Address realm-specific foundational knowledge gaps to strengthen the coastal assessment**

-   See realm-specific pages for foundational knowledge gaps; addressing these would contribute to strengthening the coastal assessment. <!--# Insert links to other realm pages -->

</details>

<details>

<summary>**Pressures, pressure impacts and monitoring**</summary>

**4. Map pressures and assess ecological condition at appropriate scales**

-   Refine the maps of pressures, particularly at the land-sea interface across the dunes and the shore.

-   Ensure coastal pressures (especially in the seashore) are mapped at an appropriate resolution.

-   Update the pressure maps where the data have become outdated.

**5. Map additional terrestrial pressures to include degradation as part of assessing ecological condition**

-   Coordinate national effort to measure, model, and map ecological condition in the terrestrial realm at a scale suitable for Red List of Ecosystem assessments and for reporting on international indicators.

**6. Determine freshwater- and sediment-flow requirements for coastal and marine systems**

-   Quantify the ecological flow requirements for all of South Africa’s estuaries, enhance understanding of the role of freshwater flow to offshore marine environments, and map of fluvial fans and plumes to support the classification and mapping of mud habitats.

-   Investigate sediment flows to beaches nationally to quantify contributions from different sand sources, and determine which beaches are being lost to erosion because they are losing sand at rates over and above natural cycles of sand loss and gain.

**7. Collect long-term data to improve models of climate change, and track impacts to coastal biodiversity**

-   Develop and implement a cohesive framework and indicators to track biodiversity and ecosystem service impacts as a result of climate change, identify critical thresholds or points of non-return, and assess the effectiveness of interventions to minimise these impacts.

-   Ensure that reliable weather station data are available throughout the South African coast.

**8. Map and better understand the impact of emerging pressures on coastal biodiversity**

-   Improve understanding of emerging pressures, e.g., various forms of pollution (chemicals, pharmaceuticals, microplastics, light and noise), renewable energy, invasive species, and climate change.

-   Map impacts of these pressures for inclusion in future assessments.

**9. Improve understanding of ecosystem degradation and links between pressures and impacts**

-   Improve understanding of interactions and impacts among pressures, and of cross-realm impacts to biodiversity.

**10. Groundtruth and refine thresholds for classifying ecological condition from habitat degradation**

-   Groundtruth maps of ecological condition with in situ measures and indicators, and use these to confirm thresholds for the categories of ecological condition.

**11. Invest in strategic long-term coastal biodiversity monitoring programmes**

-   Coordinate monitoring programmes that cover a range of taxa and a range of ecosystem types , e.g., Shallow Marine and Coastal Research Infrastructure (SMCRI).

    </details>

<details>

<summary>**Assessment**</summary>

**12. Improve application of the IUCN Red List of Ecosystems criteria by testing scale and thresholds and creating models of ecosystem collapse**

-   Develop conceptual models of ecosystem collapse.

-   Continue testing different approaches to applying the IUCN Red List of Ecosystems criteria and thresholds, in alignment with the latest guidelines, to advance red listing coastal ecosystem types.

**13. Investigate the effectiveness of protected areas in conserving biodiversity as a second indicator for ecosystem protection level**

-   Build on existing research to better understand effectiveness of protected areas in conserving coastal biodiversity, particularly cross-realm.

**14. Increase Red Listing of species, especially invertebrate and cross-realm species**

-   Prioritise assessment and monitoring of coastal species, including assessment of full taxonomic groups, of coastal species with high levels of potential threat, particularly endemic taxa (including invertebrates) and those that cross realms.

**15. Update and increase the number of fisheries stock status assessments**

-   Increase reliable data for stock status assessments.

-   Increase the number of national stock assessments (especially for highly utilised economically important species).

**16. Assess the protection level of coastal species**

-   Assess the two components of species protection level: representation and effectiveness. This will need to be backed up with research on management effectiveness of protected areas for coastal taxa.

**17. Map and assess the status of coastal ecological infrastructure**

-   Map critical ecological infrastructure and assess its status. Systematic mapping of critical ecological infrastructure could be integrated into CBA Maps to add value to spatial planning and prioritisation towards securing the many benefits South Africans gain from coastal biodiversity

</details>

<details>

<summary>**Benefits and messaging**</summary>

**18. Collect data and knowledge on the benefits of coastal biodiversity**

-   Improve collation of economic data, updated statistics on jobs and spatial data on biodiversity benefits.

**19. Identify strategies of communicating the benefits of biodiversity that most inspire action for change**

-   Test and identify methods of communication that best inspire action for change to complement communicating the results of the benefits of coastal biodiversity to people.

</details>

## Way forward

Restoring, managing and conserving coastal biodiversity in South Africa are key steps towards sustainable development, securing jobs and livelihoods, alleviating poverty, and enhancing human health and wellbeing. These actions also align well with the [United Nations Decade on Ecosystem Restoration 2021-2030](https://www.decadeonrestoration.org/){target="_blank"} and [Targets in the Kunming-Montreal Global Biodiversity Framework](https://www.cbd.int/gbf/targets){target="_blank"}.

Now more than ever, South Africa is poised to secure key coastal biodiversity and ecological infrastructure: half the coast is in natural to near-natural ecological condition, and the integrated map of ecosystem types[@harris2025b; @harris2019] and results from this assessment pave the way for better biodiversity planning, management and decision-making in the coastal zone.

Cross-realm planning is essential to ensure that land-sea ecological processes and species distributions are adequately accounted for in land-based and marine Spatial Biodiversity Plans (Maps of Critical Biodiversity Areas and Ecological Support Areas - CBA Maps, and associated land and sea-use guidelines). These Spatial Biodiversity Plans are a key tool by which to align governance, planning and decision-making across realms and across organs of state to achieve effective, science-based and proactive integrated coastal zone management [@harris2025a].

## Publication {#publication}

Harris, L.R., Skowno, A.L., Sink, K.J., Van Niekerk, L., Holness, S.D., Monyeki, M., Majiedt, P., 2022. **An indicator-based approach for cross-realm coastal biodiversity assessments.** African Journal of Marine Science 44, 239-253. <https://doi.org/10.2989/1814232X.2022.2104373>\
*The research gaps and research priorities presented here have been published as supplementary material in this paper*

### Data availability

The following datasets are available for download (@harris2025a):

[Cross-realm coastal biodiversity priority areas Version 1](https://figshare.com/articles/dataset/Coastal_Biodiversity_Priority_Areas_2023/22463890?file=39915325){target="_blank"}

[National Seashore and Estuary CBA Map Version 1](https://figshare.com/articles/dataset/National_Seashore_and_Estuary_CBA_Map/22461901?file=40064239)

### Related publications and supporting information

Harris, L.R., van Niekerk, L., Holness, S.D., Sink, K.J., Skowno, A.L., Dayaram, A., van Deventer, H., Job, N., Lamberth, S.J., Adams, J.B., Raw, J.L., Riddin, T., MacKay, C.F., Perschke, M.J., 2025. **Conserving cross-realm coastal biodiversity when real-world planning and implementation processes split the land and sea**. Ocean & Coastal Management 263, 107586. <https://doi.org/10.1016/j.ocecoaman.2025.107586>\
*Technical details regarding cross-realm conservation planning to ensure inclusion of land-sea processes and biodiversity, with proposed management recommendations for restoring and conserving coastal biodiversity*

Harris, L.R., Sink, K.J., Skowno, A.L., Van Niekerk, L. eds., 2021. **South African National Biodiversity Assessment 2018 Technical Report Volume 5: Coast**. South African National Biodiversity Institute, Pretoria. <http://hdl.handle.net/20.500.12143/6374.>\
*Full details on priority actions, knowledge gaps and research priorities are available in the technical report from the NBA 2018, updated in 2021*

## Recommended citation

The [publication](#publication) is the preferred citation for this content, otherwise use:

```{r}
#| output: asis
#| label: lst-citation-code

library(nbaR) 
library(knitr)
library(rmarkdown)

# Code for fetching the yaml metadata
# Note that this only runs when the .qmd file is rendered, therefore the outputs of this code block will return no results if you try to run it within R - that does not mean it is not working

meta <- knitr::opts_knit$get("rmarkdown.pandoc.to")  # forces knitr to load metadata
meta <- rmarkdown::metadata  # full YAML is now in `meta`

nba_citation(meta)

```

## References

::: {#refs}
:::
