---
# indentations are critical in YAML headers, be careful when editing this section

title: "Wetland ecosystem types" # Compulsory
subtitle: "Freshwater (inland aquatic) realm" # Optional: delete if you are not using a subtitle

title-block-banner: "#4097C2" #Background colour of the title block: Apply component colours where necessary - find hex codes in _brand.yml
title-block-banner-color: white # Header text colour: DO NOT CHANGE

# List authors here in the order you want them displayed in the title block
# See examples in README
author:
 # Copy this block and add details for each author of your page. Make sure you maintain indentations exactly as they are here
  - name:
      given: Nancy
      family: Job
    orcid: 0000-0000-0000-0000  
    affiliations:
      - ref: sanbi
  - name:
      given: Suzanne 
      family: Grenfell 
    orcid: 0000-0000-0000-0000  
    affiliations:
      - ref: ustell  
  - name:
      given: Dean 
      family: Ollis 
    orcid: 0000-0002-4929-7592 
    affiliations:
      - ref: inlandwaters
  - name:
      given: Donovan 
      family: Kotze 
    orcid: 000-0000-0000-0000 
    affiliations:
      - ref: ukzn    
  - name:
      given: Nacelle B.
      family: Collins 
    orcid: 0000-0000-0000-0000  
    affiliations:
      - ref: destea 
      # If an author has more than one affiliation, add more - ref: lines here
  - name:
      given: Adwoa 
      family: Awuah 
    orcid: 0000-0002-4929-7592 
    affiliations:
      - ref: sanbi 
  - name:
      given: Erwin
      family: Sieben
    orcid: 0000-0000-0000-0000  
    affiliations:
      - ref: ukzn 
      
affiliations:
# List affiliations here and number them in the order that they are associated with the list of authors above. If multiple authors have the same affiliation, only list the affiliation once here.
# Write out institutional names in full
# See README for common examples - they can be copied and pasted here
# Make sure you maintain indentations exactly as they are here
  - id: sanbi 
    number: 1 
    name: South African National Biodiversity Institute
  - id: ustell 
    number: 2 
    name: University of Stellenbosch
  - id: inlandwaters 
    number: 3
    name: Inland Waters
  - id: ukzn 
    number: 4 
    name: University of KwaZulu-Natal
  - id: destea 
    number: 5      
    name: Free State Department of Economic, Small Business Development, Tourism and Environmental Affairs

# This date determines the PUBLISHED date in the title block
date: last-modified

# Remember to rename the default .bib file and change the name here
bibliography: fw-references.bib

# This section sets up the page citation format. DO NOT EDIT
citation:
  type: webpage
  container-title: National Biodiversity Assessment 2025
  publisher: South African National Biodiversity Institute
  url: http://nba.sanbi.org.za/
# Do not edit or change any of the following entries
appendix-cite-as: false
google-scholar: true
---

*South Africa’s globally recognised biodiversity richness also extends to inland wetlands. A wide range of climatic, geological and topographic settings have resulted in an exceptional diversity of wetland ecosystem types, from permanently saturated peatlands that accumulated in place over thousands of years to ephemeral salt pans harbouring newly described invertebrate species. In global terms, South Africa’s wetlands are small, with nearly 50% that are less than 1.5 hectares in size, but they are of outsized importance in a semi-arid context and they frequently function as an inter-connected network across a catchment. Wetlands provide vitally important benefits to people, such as improving water quality and controlling floods. They are water sources, habitats, and refuges for animals and people in times of drought.*

We have an interim typology in place and are currently at work on an updated national system to understand and manage our wetlands as effectively as possible. The proposed updated typology update will contribute significantly towards ensuring their long-term health and the benefits they provide to all South Africans.

::: {#box-1 .callout-note .freshwater title="Box 1. xxxxxxxx" collapse="true"}
WetMap

Digital Earth Africa

Field campaigns and photo

EcoPulse, Phil and team
:::

::: {.callout-note .freshwater title="Box 4. Wetlands of International Importance (Ramsar Wetlands)" collapse="true"}
Prepared by .
:::

## Approach to develop this input layer

measures

## Acknowledgements

Major contributors to the National Wetland Map

## Technical documentation

**Code repository**: nwm link

**Key Publications**:

Ollis

Grenfell

Floodplains infosheet

Collins WetMap

**Technical reports**:

SANBI. 2025. National Wetland Map: South Africa’s official map of wetland extent, type and condition. SANBI Factsheet series. South African National Biodiversity Institute, Pretoria.

## Recommended citation

Job, N.M., Skowno, A.L xx. 2025. Ecosystem protection level: Freshwater (inland aquatic) realm synthesis. National Biodiversity Assessment 2025. South African National Biodiversity Institute. http://nba.sanbi.org.za/.

## References

::: {#refs}
:::
